<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to the General Linear Model - 11&nbsp; Inferences about a Continuous and Dichotomous Predictor and their Interaction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12_interactions_two_dichotomous.html" rel="next">
<link href="./10_interactions_two_continuous.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="book.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11_interactions_continuous_and_dichotomous.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inferences about a Continuous and Dichotomous Predictor and their Interaction</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to the General Linear Model</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/jjcurtin/book_glm" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_sampling_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sampling Distributions, Parameters, and Parameter Estimates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_single_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferences About a Single Mean (1 Parameter Models)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_single_quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inferences About a Single Quantitative Predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_single_dichotomous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inferences about a Single Dichotomous Predictor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_two_predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Inferences about two predictors (multiple regression without interaction)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_case_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dealing with Messy Data I: Case Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_model_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Dealing with Messy Data II: Model Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Dealing with Messy Data III: Transformations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_interactions_two_continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inferences about Two Continuous Predictors and their Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_interactions_continuous_and_dichotomous.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inferences about a Continuous and Dichotomous Predictor and their Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_interactions_two_dichotomous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferences about a Two Dichotomous Predictors and their Interaction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_categorical_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Categorical Variables &gt; 2 Levels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Power Analysis and Statistical Validity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_the_generalized_linear_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Generalized Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app_terminology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Key Terminology and Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repeated_measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Repeated Measures</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#interactive-models-quantitative-and-dichotomous" id="toc-interactive-models-quantitative-and-dichotomous" class="nav-link active" data-scroll-target="#interactive-models-quantitative-and-dichotomous"><span class="header-section-number">11.1</span> Interactive Models: Quantitative and Dichotomous</a></li>
  <li><a href="#quantitative-dichotomous-predictor-main-effects" id="toc-quantitative-dichotomous-predictor-main-effects" class="nav-link" data-scroll-target="#quantitative-dichotomous-predictor-main-effects"><span class="header-section-number">11.2</span> Quantitative &amp; Dichotomous: Predictor <em>Main</em> effects</a></li>
  <li><a href="#quantitative-dichotomous-predictor-simple-effects" id="toc-quantitative-dichotomous-predictor-simple-effects" class="nav-link" data-scroll-target="#quantitative-dichotomous-predictor-simple-effects"><span class="header-section-number">11.3</span> Quantitative &amp; Dichotomous: Predictor <em>simple</em> effects</a></li>
  <li><a href="#quantitative-dichotomous-dichotomous-simple-effects" id="toc-quantitative-dichotomous-dichotomous-simple-effects" class="nav-link" data-scroll-target="#quantitative-dichotomous-dichotomous-simple-effects"><span class="header-section-number">11.4</span> Quantitative &amp; Dichotomous: Dichotomous <em>simple</em> effects</a></li>
  <li><a href="#a-sample-brief-report-defendant-race-is-focal" id="toc-a-sample-brief-report-defendant-race-is-focal" class="nav-link" data-scroll-target="#a-sample-brief-report-defendant-race-is-focal"><span class="header-section-number">11.5</span> A sample brief report: Defendant race is focal</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jjcurtin/book_glm/edit/main/11_interactions_continuous_and_dichotomous.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inferences about a Continuous and Dichotomous Predictor and their Interaction</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="interactive-models-quantitative-and-dichotomous" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="interactive-models-quantitative-and-dichotomous"><span class="header-section-number">11.1</span> Interactive Models: Quantitative and Dichotomous</h2>
<p><strong>Example:</strong></p>
<p>Effect of juror implicit bias (0-100) and race of defendant (White = 0; Black =1) on ratings of defendant guilt (0-100).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">conflicts.policy =</span> <span class="st">"depends.ok"</span>) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_classic</span>()) </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>path_data <span class="ot">&lt;-</span> <span class="st">"data_lecture"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(path_data, <span class="st">"11_interactions_jurors.csv"</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 240
Columns: 4
$ subid        &lt;chr&gt; "001", "002", "003", "004", "005", "006", "007", "008", "…
$ black_defend &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ bias         &lt;dbl&gt; 42.53833, 52.55506, 57.25757, 46.99403, 52.21168, 18.8001…
$ guilt        &lt;dbl&gt; 40.83539, 44.44454, 47.90421, 57.45485, 62.45751, 18.2372…</code></pre>
</div>
</div>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(black_defend<span class="sc">:</span>guilt, <span class="at">names_to =</span> <span class="st">"var"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(var) <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(value), </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(value), </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(value), </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  var           mean     sd   min   max
  &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 bias          34.7 16.2    3.86  63.3
2 black_defend   0.5  0.501  0      1  
3 guilt         43.8 18.1   16.7   93.4</code></pre>
</div>
</div>
<p><span style="color: red;">Question: How do you conduct an ANCOVA analysis in regression using bias as a covariate?</span></p>
<hr>
<p><span style="color: blue;">Regress guilt on defendant race and bias in an additive model. Test &amp; interpret bias effect.</span></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m_add <span class="ot">&lt;-</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend <span class="sc">+</span> bias, <span class="at">data =</span> data)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>m_add <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    11.8      2.02        5.84 1.71e- 8
2 black_defend    8.50     1.56        5.45 1.28e- 7
3 bias            0.799    0.0484     16.5  2.83e-41</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m_add)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %   97.5 %
(Intercept)  7.8288544 15.79898
black_defend 5.4267932 11.57569
bias         0.7039293  0.89468</code></pre>
</div>
</div>
<p><span class="math inline">\(\eta_p^2\)</span> for bias</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend, data))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(m_add)<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend, data))<span class="sc">^</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5349119</code></pre>
</div>
</div>
<p><span style="color: red;">Question: What do we conclude? What do we report?</span></p>
<hr>
<p><span style="color: red;">Question: What is the specific interpretation in terms of the effect of defendant race?</span></p>
<hr>
<p><span style="color: blue;">On average, Black defendants are judged to be 8.5 units more guilty than White defendants, controlling for (holding constant) implicit bias.</span></p>
<hr>
<p><span style="color: red;">Question: What does this model require with respect to this group comparison across various levels of implicit bias?</span></p>
<hr>
<p><span style="color: blue;">It requires that the magnitude of the Black defendant (vs.&nbsp;White defendant) group difference (<span class="math inline">\(b=8.5\)</span>) be the same for all levels of implicit bias <strong>and</strong> the bias effect be the same for both defendant races.</span></p>
<hr>
<p><span style="color: red;">Question: How can you remove that constraint?</span></p>
<hr>
<p><span style="color: blue;">Include an interaction between defendent race and bias.</span></p>
<p><span style="color: red;">Question: But what is now important to do with <span class="math inline">\(X\)</span>s?</span></p>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">black_defend_c =</span> <span class="fu">if_else</span>(black_defend <span class="sc">==</span> <span class="dv">0</span>, <span class="sc">-</span>.<span class="dv">5</span>, .<span class="dv">5</span>),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_c =</span> bias <span class="sc">-</span> <span class="fu">mean</span>(bias))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Always check that your transformations work as expected (mean, min, max, N, exemplar values).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_head</span>(data, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  subid black_defend  bias guilt black_defend_c bias_c
  &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;  &lt;dbl&gt;
1 001              0  42.5  40.8           -0.5   7.86
2 002              0  52.6  44.4           -0.5  17.9 
3 003              0  57.3  47.9           -0.5  22.6 
4 004              0  47.0  57.5           -0.5  12.3 
5 005              0  52.2  62.5           -0.5  17.5 </code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(black_defend_c, bias_c), <span class="at">names_to =</span> <span class="st">"var"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(var) <span class="sc">|&gt;</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(value), </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(value), </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(value), </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  var                 mean     sd   min   max
  &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 bias_c         -1.97e-15 16.2   -30.8  28.7
2 black_defend_c  0         0.501  -0.5   0.5</code></pre>
</div>
</div>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>m_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">*</span> bias_c, <span class="at">data =</span> data)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>m_int <span class="sc">|&gt;</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                  estimate std.error statistic   p.value
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             43.9      0.751      58.4  2.78e-142
2 black_defend_c           8.50     1.50        5.66 4.40e-  8
3 bias_c                   0.797    0.0466     17.1  3.24e- 43
4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                           2.5 %     97.5 %
(Intercept)           42.3761677 45.3354438
black_defend_c         5.5405532 11.4591055
bias_c                 0.7054229  0.8890371
black_defend_c:bias_c  0.2312938  0.5985222</code></pre>
</div>
</div>
<p><span class="math inline">\(\eta_p^2\)</span> for interaction between bias and defendent race (centered)</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">+</span> bias_c, data))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(m_int)<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">+</span> bias_c, data))<span class="sc">^</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07746803</code></pre>
</div>
</div>
<p><span class="math inline">\(\eta_p^2\)</span> for bias (centered)</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">+</span> bias_c<span class="sc">:</span>black_defend_c, data))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(m_int)<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">+</span> bias_c<span class="sc">:</span>black_defend_c, data))<span class="sc">^</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5535959</code></pre>
</div>
</div>
<p><span class="math inline">\(\eta_p^2\)</span> for defendant race (centered)</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> bias_c <span class="sc">+</span> bias_c<span class="sc">:</span>black_defend_c, data))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(m_int)<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">residuals</span>(<span class="fu">lm</span>(guilt <span class="sc">~</span> bias_c <span class="sc">+</span> bias_c<span class="sc">:</span>black_defend_c, data))<span class="sc">^</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1194663</code></pre>
</div>
</div>
<hr>
<p><strong>Additive Model:</strong></p>
<p><span class="math inline">\(\text{guilt} = 11.8 + 8.5*\text{black defend} + 0.8*\text{bias}\)</span></p>
<p><strong>Interactive Model:</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><span style="color: red;">Link model coefficients to each figure.</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>preds_add <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">bias =</span> <span class="fu">seq</span>(<span class="dv">3</span>, <span class="dv">65</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="at">black_defend =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>preds_y_add <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_add, <span class="at">newdata =</span> preds_add, <span class="at">se.fit =</span> <span class="cn">TRUE</span>) </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>plot_add <span class="ot">&lt;-</span> preds_add <span class="sc">|&gt;</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(preds_y_add) <span class="sc">|&gt;</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span>  </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">upper =</span> fit <span class="sc">+</span> se.fit,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">lower=</span> fit <span class="sc">-</span> se.fit) <span class="sc">|&gt;</span> </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> bias, <span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper, </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">group =</span> <span class="fu">factor</span>(black_defend, </span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"White"</span>, <span class="st">"Black"</span>))), </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> bias, <span class="at">y =</span> fit, </span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="fu">factor</span>(black_defend, </span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"White"</span>, <span class="st">"Black"</span>))), </span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Juror Implicit Bias"</span>,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Defendant Guilt"</span>,</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Defendant Race"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>m_int_raw <span class="ot">&lt;-</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend <span class="sc">*</span> bias, <span class="at">data =</span> data)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>preds_int <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">bias =</span> <span class="fu">seq</span>(<span class="dv">3</span>, <span class="dv">65</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="at">black_defend =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>preds_y_int <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_int_raw, <span class="at">newdata =</span> preds_int, <span class="at">se.fit =</span> <span class="cn">TRUE</span>) </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>preds_int <span class="ot">&lt;-</span> preds_int <span class="sc">|&gt;</span> </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(preds_y_int) <span class="sc">|&gt;</span> </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span>  </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">upper =</span> fit <span class="sc">+</span> se.fit,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">lower=</span> fit <span class="sc">-</span> se.fit)  </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>plot_int <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> preds_int<span class="sc">$</span>bias, <span class="at">ymin =</span> preds_int<span class="sc">$</span>lower, <span class="at">ymax =</span> preds_int<span class="sc">$</span>upper, </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">group =</span> <span class="fu">factor</span>(preds_int<span class="sc">$</span>black_defend, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"White"</span>, <span class="st">"Black"</span>))), </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> preds_int<span class="sc">$</span>bias, <span class="at">y =</span> preds_int<span class="sc">$</span>fit, </span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="fu">factor</span>(preds_int<span class="sc">$</span>black_defend, </span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"White"</span>, <span class="st">"Black"</span>))), </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Juror Implicit Bias"</span>,</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Defendant Guilt"</span>,</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Defendant Race"</span>) </span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>plot_add <span class="sc">+</span> plot_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="11_interactions_continuous_and_dichotomous_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="quantitative-dichotomous-predictor-main-effects" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="quantitative-dichotomous-predictor-main-effects"><span class="header-section-number">11.2</span> Quantitative &amp; Dichotomous: Predictor <em>Main</em> effects</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>m_int <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                  estimate std.error statistic   p.value
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             43.9      0.751      58.4  2.78e-142
2 black_defend_c           8.50     1.50        5.66 4.40e-  8
3 bias_c                   0.797    0.0466     17.1  3.24e- 43
4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
</div>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: What is the interpretation of <span class="math inline">\(b= 0.8\)</span> for bias (centered)?</span></p>
<hr>
<p><span style="color: blue;">This is the unweighted effect of bias averaged across White and Black defendants.</span></p>
<p><span style="color: blue;">You can think about this like a main effect in ANOVA. For every one unit increase in bias, ratings of defendants’ guilt increased by 0.8 units when averaging across defendants of both races (holding constant race at its unweighted average), <span class="math inline">\(t(236)= 17.1, p &lt; .001\)</span>.</span></p>
<p>You should also describe the effect with the 95% CI for <span class="math inline">\(b\)</span> and a variance effect size estimate.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>preds_effect_bias <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_int_raw, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">tibble</span>(<span class="at">black_defend =</span> .<span class="dv">5</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">bias =</span> <span class="fu">seq</span>(<span class="dv">3</span>, <span class="dv">65</span>, <span class="at">by =</span> <span class="dv">1</span>)), </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">tibble</span>(<span class="at">black_defend =</span> .<span class="dv">5</span>, <span class="at">bias =</span> <span class="fu">seq</span>(<span class="dv">3</span>, <span class="dv">65</span>, <span class="at">by =</span> <span class="dv">1</span>))) </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>plot_int <span class="ot">&lt;-</span> plot_int <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> preds_effect_bias<span class="sc">$</span>bias,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> preds_effect_bias<span class="sc">$</span>fit), </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> .<span class="dv">75</span>)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>plot_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="11_interactions_continuous_and_dichotomous_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>m_int <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                  estimate std.error statistic   p.value
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             43.9      0.751      58.4  2.78e-142
2 black_defend_c           8.50     1.50        5.66 4.40e-  8
3 bias_c                   0.797    0.0466     17.1  3.24e- 43
4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
</div>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: What is the interpretation of <span class="math inline">\(b= 8.5\)</span> for defendent race (centered)?</span></p>
<hr>
<p><span style="color: blue;">This is the effect of defendent race for participants of average implicit bias. You can think about this like a main effect in ANOVA.</span></p>
<p><span style="color: blue;">Black defendants are rated 8.5 units more guilty than White defendants among jurors with average bias (holding constant bias at its mean), <span class="math inline">\(t(236) = 5.66, p &lt; .001\)</span>.</span></p>
<p>You should also describe the effect with the 95% CI for <span class="math inline">\(b\)</span> and a variance effect size estimate.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>plot_int <span class="ot">&lt;-</span> plot_int <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(data<span class="sc">$</span>bias), <span class="at">linewidth =</span> .<span class="dv">75</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>plot_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="11_interactions_continuous_and_dichotomous_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m_int <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                  estimate std.error statistic   p.value
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             43.9      0.751      58.4  2.78e-142
2 black_defend_c           8.50     1.50        5.66 4.40e-  8
3 bias_c                   0.797    0.0466     17.1  3.24e- 43
4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
</div>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: How do we test for the interaction between Bias and Defendant Race on Guilt?</span></p>
<hr>
<p><span style="color: blue;">The test of the <span class="math inline">\(b\)</span> for the product term (defendent race X bias) is the test of the interaction. It is significant, <span class="math inline">\(t(236)= 4.45, p&lt; .001\)</span>.</span></p>
<hr>
<p><span style="color: red;">Question: What does this mean to have an interaction and how do you interpret <span class="math inline">\(b = 0.4\)</span>?</span></p>
<hr>
<p><span style="color: blue;">The magnitude of the effect of defendant race on guilt increases by 0.4 units for every one unit increase in bias.</span></p>
<p><span style="color: blue;">The magnitude of the effect of bias is 0.4 units greater when the defendants are Black than when they are White.</span></p>
<hr>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>plot_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="11_interactions_continuous_and_dichotomous_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The slopes of the lines differ by 0.4 <strong>or</strong></p></li>
<li><p>The separation of the lines increases by 0.4 for every 1 unit increase in bias.</p></li>
</ul>
<hr>
</section>
<section id="quantitative-dichotomous-predictor-simple-effects" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="quantitative-dichotomous-predictor-simple-effects"><span class="header-section-number">11.3</span> Quantitative &amp; Dichotomous: Predictor <em>simple</em> effects</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>m_int <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                  estimate std.error statistic   p.value
  &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)             43.9      0.751      58.4  2.78e-142
2 black_defend_c           8.50     1.50        5.66 4.40e-  8
3 bias_c                   0.797    0.0466     17.1  3.24e- 43
4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
</div>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: How do you quantify and test the simple effects of bias, separately for Whites and Blacks? What are these two simple effects on the previous figure?</span></p>
<hr>
<p><span style="color: blue;">Simple effects of bias are represented as the slopes of the two lines.</span></p>
<p><span style="color: blue;">Fit two interactive models with dummy coding for defendent race - one with White = 0 for <strong>White</strong> simple effect and one with Black = 0 for <strong>Black</strong> simple effect.</span></p>
<p><span style="color: blue;">In each of these models, <span class="math inline">\(b\)</span> for bias will be the simple effect for group coded as 0.</span></p>
<p><span style="color: red;">Question: What should the coefficients be (think about it)?</span></p>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m_white <span class="ot">&lt;-</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend <span class="sc">*</span> bias_c, <span class="at">data =</span> data)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>m_white <span class="sc">|&gt;</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                estimate std.error statistic   p.value
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           39.6      1.06       37.3  6.72e-101
2 black_defend           8.50     1.50        5.66 4.40e-  8
3 bias_c                 0.590    0.0662      8.90 1.46e- 16
4 black_defend:bias_c    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">white_defend =</span> <span class="dv">1</span> <span class="sc">-</span> black_defend)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>m_black <span class="ot">&lt;-</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> white_defend <span class="sc">*</span> bias_c, <span class="at">data =</span> data)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>m_black <span class="sc">|&gt;</span> </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                estimate std.error statistic   p.value
  &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           48.1      1.06       45.3  2.20e-118
2 white_defend          -8.50     1.50       -5.66 4.40e-  8
3 bias_c                 1.00     0.0656     15.3  3.01e- 37
4 white_defend:bias_c   -0.415    0.0932     -4.45 1.31e-  5</code></pre>
</div>
</div>
<hr>
<p><strong>Centered model</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Dummy, White = 0</strong><br>
<span class="math inline">\(\text{guilt} = 39.6 + 8.5*\text{black defend} + 0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span></p>
<p><strong>Dummy, Black = 0</strong><br>
<span class="math inline">\(\text{guilt} = 48.1 + -8.5*\text{white defend} + 1.0*\text{bias}_c + -.4*\text{white defend}*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of the intercept in each model?</span></p>
<hr>
<p><span style="color: blue;">Centered: Predicted guilt rating unweighted across defendant race for juror of average bias.</span></p>
<p><span style="color: blue;">Dummy/White as 0: Predicted guilt rating for White defendant for juror of average bias.</span></p>
<p><span style="color: blue;">Dummy/Black as 0: Predicted guilt rating for Black defendant for juror of average bias.</span></p>
<hr>
<p><strong>Centered model</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Dummy, White = 0</strong><br>
<span class="math inline">\(\text{guilt} = 39.6 + 8.5*\text{black defend} + 0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span></p>
<p><strong>Dummy, Black = 0</strong><br>
<span class="math inline">\(\text{guilt} = 48.1 + -8.5*\text{white defend} + 1.0*\text{bias}_c + -.4*\text{white defend}*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of <span class="math inline">\(b\)</span> for defendant race in each model?</span></p>
<hr>
<p><span style="color: blue;">Centered: The contrast of mean guilt ratings for Black vs.&nbsp;White defendants for jurors of average bias.</span></p>
<p><span style="color: blue;">Dummy/White as 0: The contrast of mean guilt ratings for Black vs.&nbsp;White defendants for jurors of average bias.</span></p>
<p><span style="color: blue;">Dummy/Black as 0: The contrast of mean guilt ratings for White vs.&nbsp;Black defendants for jurors of average bias.</span></p>
<hr>
<p><strong>Centered model</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Dummy, White = 0</strong><br>
<span class="math inline">\(\text{guilt} = 39.6 + 8.5*\text{black defend} + 0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span></p>
<p><strong>Dummy, Black = 0</strong><br>
<span class="math inline">\(\text{guilt} = 48.1 + -8.5*\text{white defend} + 1.0*\text{bias}_c + -.4*\text{white defend}*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of <span class="math inline">\(b\)</span> for bias in each model?</span></p>
<hr>
<p><span style="color: blue;">Centered: The change in guilt for a 1 unit increase in bias, unweighted/averaged across defendant race.</span></p>
<p><span style="color: blue;">Dummy/White as 0: The change in guilt for a 1 unit increase in bias for White defendants.</span></p>
<p><span style="color: blue;">Dummy/Black as 0: The change in guilt for a 1 unit increase in bias for Black defendants.</span></p>
<hr>
<p><strong>Centered model</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Dummy, White = 0</strong><br>
<span class="math inline">\(\text{guilt} = 39.6 + 8.5*\text{black defend} + 0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span></p>
<p><strong>Dummy, Black = 0</strong><br>
<span class="math inline">\(\text{guilt} = 48.1 + -8.5*\text{white defend} + 1.0*\text{bias}_c + -.4*\text{white defend}*\text{bias}_c\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of <span class="math inline">\(b\)</span> for product term in each model (from a bias effect perspective)?</span></p>
<hr>
<p><span style="color: blue;">Centered: The change in the magnitude of the bias effect for a one unit change in defendant race (White to Black).</span></p>
<p><span style="color: blue;">Dummy/White as 0: The change in the magnitude of the bias effect for a one unit change in defendant race (White to Black).</span></p>
<p><span style="color: blue;">Dummy/Black as 0: The change in the magnitude of the bias effect for a one unit change in defendant race (Black to White).</span></p>
<hr>
<p><strong>Centered model</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Dummy, White = 0</strong><br>
<span class="math inline">\(\text{guilt} = 39.6 + 8.5*\text{black defend} + 0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span></p>
<p><strong>Dummy, Black = 0</strong><br>
<span class="math inline">\(\text{guilt} = 48.1 + -8.5*\text{white defend} + 1.0*\text{bias}_c + -.4*\text{white defend}*\text{bias}_c\)</span></p>
<p><span style="color: red;">Quantify effect of bias from model formula (can use any model).</span></p>
<hr>
<p><strong>From Dummy, White = 0 model</strong></p>
<p><span style="color: blue;">For Whites:</span></p>
<p>Bias effect = <span class="math inline">\(0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span><br>
Bias effect = <span class="math inline">\(0.6*\text{bias}_c + .4*0*\text{bias}_c\)</span><br>
Bias effect = <span class="math inline">\(0.6*\text{bias}_c\)</span></p>
<p><span style="color: blue;">For Blacks:</span></p>
<p>Bias effect = <span class="math inline">\(0.6*\text{bias}_c + .4*\text{black defend}*\text{bias}_c\)</span><br>
Bias effect = <span class="math inline">\(0.6*\text{bias}_c + .4*1*\text{bias}_c\)</span><br>
Bias effect = <span class="math inline">\(1.0*\text{bias}_c\)</span></p>
<hr>
</section>
<section id="quantitative-dichotomous-dichotomous-simple-effects" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="quantitative-dichotomous-dichotomous-simple-effects"><span class="header-section-number">11.4</span> Quantitative &amp; Dichotomous: Dichotomous <em>simple</em> effects</h2>
<p><span style="color: red;">Question: How do you test simple effects of defendant race at various levels of bias (and what levels might you choose to test)?</span></p>
<hr>
<p><span style="color: blue;">We want to report simple effects of defendant race at the mean of bias and one SD above and below mean (or other meaningful values).</span></p>
<p><span style="color: blue;">Make sure the that the levels of bias at <span class="math inline">\(\pm1\)</span> SD are represented in your data!</span></p>
<p><span style="color: blue;">As we noted earlier, the coefficient for defendant race (8.5) from the centered model is the simple effect of defendant race at the mean of bias.</span></p>
<p><span style="color: blue;">We need to perform two more transformations of bias to get the other simple effect tests for defendant race.</span></p>
<hr>
<p><strong>Centered model</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p>Bias is centered such that 0 = mean of bias.</p>
<p>We need to transform bias such that 0 = +1 SD of bias or -1 SD of bias.</p>
<p>It is counter-intuitive so be careful!</p>
<p>+1 SD = 0</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bias_hi =</span> bias_c <span class="sc">-</span> <span class="fu">sd</span>(bias_c))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>-1 SD = 0</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bias_lo =</span> bias_c <span class="sc">+</span> <span class="fu">sd</span>(bias_c))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><em>Note</em>: It is easy to confuse these transformations. Do a logical check on your results.</p>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>m_bias_hi <span class="ot">=</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">*</span> bias_hi, <span class="at">data =</span> data)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>m_bias_hi <span class="sc">|&gt;</span> </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                   estimate std.error statistic   p.value
  &lt;chr&gt;                     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)              56.7      1.06       53.4  1.07e-133
2 black_defend_c           15.2      2.13        7.15 1.09e- 11
3 bias_hi                   0.797    0.0466     17.1  3.24e- 43
4 black_defend_c:bias_hi    0.415    0.0932      4.45 1.31e-  5</code></pre>
</div>
</div>
<p>For Jurors who are highly biased, Black defendants are rated 15.2 units more guilty than White defendants.</p>
<hr>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>m_bias_lo <span class="ot">=</span> <span class="fu">lm</span>(guilt <span class="sc">~</span> black_defend_c <span class="sc">*</span> bias_lo, <span class="at">data =</span> data)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>m_bias_lo <span class="sc">|&gt;</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                   estimate std.error statistic  p.value
  &lt;chr&gt;                     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)              31.0      1.06      29.1   4.03e-80
2 black_defend_c            1.80     2.13       0.846 3.99e- 1
3 bias_lo                   0.797    0.0466    17.1   3.24e-43
4 black_defend_c:bias_lo    0.415    0.0932     4.45  1.31e- 5</code></pre>
</div>
</div>
<p>For Jurors who are highly unbiased, Black defendants are rated 1.8 units more guilty than White defendants.</p>
<hr>
<p><strong>Mean centered bias</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Centered on -1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 31.0 + 1.8*\text{black defend}_c + 0.8*\text{bias}_l + .4*\text{black defend}_c*\text{bias}_l\)</span></p>
<p><strong>Centered on +1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 56.7 + 15.2*\text{black defend}_c + 0.8*\text{bias}_h + .4*\text{black defend}_c*\text{bias}_h\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of the intercept in each model?</span></p>
<hr>
<p><span style="color: blue;">Mean: Predicted guilt rating unweighted across defendant race for juror of average bias.</span></p>
<p><span style="color: blue;">-1 SD: Predicted guilt rating for jurors who are low on bias, unweighted across defendant race.</span></p>
<p><span style="color: blue;">+1 SD: Predicted guilt rating for jurors who are high on bias, unweighted across defendant race.</span></p>
<hr>
<p><strong>Mean centered bias</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Centered on -1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 31.0 + 1.8*\text{black defend}_c + 0.8*\text{bias}_l + .4*\text{black defend}_c*\text{bias}_l\)</span></p>
<p><strong>Centered on +1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 56.7 + 15.2*\text{black defend}_c + 0.8*\text{bias}_h + .4*\text{black defend}_c*\text{bias}_h\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of <span class="math inline">\(b\)</span> for defendant race in each model?</span></p>
<hr>
<p><span style="color: blue;">Mean: The contrast of mean guilt ratings for Black vs.&nbsp;White defendants for jurors of average bias (main effect).</span></p>
<p><span style="color: blue;">-1 SD: The contrast of mean guilt ratings for Black vs.&nbsp;White defendants for jurors low on bias (simple effect).</span></p>
<p><span style="color: blue;">+1 SD: The contrast of mean guilt ratings for Black vs.&nbsp;White defendants for jurors high on bias (simple effect).</span></p>
<hr>
<p><strong>Mean centered bias</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Centered on -1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 31.0 + 1.8*\text{black defend}_c + 0.8*\text{bias}_l + .4*\text{black defend}_c*\text{bias}_l\)</span></p>
<p><strong>Centered on +1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 56.7 + 15.2*\text{black defend}_c + 0.8*\text{bias}_h + .4*\text{black defend}_c*\text{bias}_h\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of <span class="math inline">\(b\)</span> for bias in each model?</span></p>
<hr>
<p><span style="color: blue;">Mean: The change in guilt for a 1 unit increase in bias, unweighted across defendant race.</span></p>
<p><span style="color: blue;">-1 SD: The change in guilt for a 1 unit increase in bias, unweighted across defendant race.</span></p>
<p><span style="color: blue;">+1 SD: The change in guilt for a 1 unit increase in bias, unweighted across defendant race.</span></p>
<hr>
<p><strong>Mean centered bias</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Centered on -1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 31.0 + 1.8*\text{black defend}_c + 0.8*\text{bias}_l + .4*\text{black defend}_c*\text{bias}_l\)</span></p>
<p><strong>Centered on +1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 56.7 + 15.2*\text{black defend}_c + 0.8*\text{bias}_h + .4*\text{black defend}_c*\text{bias}_h\)</span></p>
<p><span style="color: red;">Question: What are the interpretations of <span class="math inline">\(b\)</span> for product term in each model (from a defendant race effect perspective)?</span></p>
<hr>
<p><span style="color: blue;">Mean: The change in the magnitude of the defendant race effect for a one unit change in juror bias.</span></p>
<p><span style="color: blue;">-1 SD: The change in the magnitude of the defendant race effect for a one unit change in juror bias.</span></p>
<p><span style="color: blue;">+1 SD: The change in the magnitude of the defendant race effect for a one unit change in juror bias.</span></p>
<hr>
<p><strong>Mean centered bias</strong></p>
<p><span class="math inline">\(\text{guilt} = 43.9 + 8.5*\text{black defend}_c + 0.8*\text{bias}_c + .4*\text{black defend}_c*\text{bias}_c\)</span></p>
<p><strong>Centered on -1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 31.0 + 1.8*\text{black defend}_c + 0.8*\text{bias}_l + .4*\text{black defend}_c*\text{bias}_l\)</span></p>
<p><strong>Centered on +1 SD for bias</strong><br>
<span class="math inline">\(\text{guilt} = 56.7 + 15.2*\text{black defend}_c + 0.8*\text{bias}_h + .4*\text{black defend}_c*\text{bias}_h\)</span></p>
<p><span style="color: red;">Quantify effect of defendant race from model formula (can use any model).</span></p>
<hr>
<p><strong>From centered model</strong></p>
<p><span style="color: blue;">Mean:</span></p>
<p>Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c + .4*\text{black defend}_c*\text{bias}_c\)</span><br>
Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c + .4*\text{black defend}_c*0\)</span><br>
Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c\)</span></p>
<p><span style="color: blue;">-1 SD:</span></p>
<p>Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c + .4*\text{black defend}_c*\text{bias}_c\)</span><br>
Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c + .4*\text{black defend}_c*-16.2\)</span><br>
Defendant race effect = <span class="math inline">\(1.8*\text{black defend}_c\)</span> (w/rounding error)</p>
<p><span style="color: blue;">+1 SD:</span></p>
<p>Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c + .4*\text{black defend}_c*\text{bias}_c\)</span><br>
Defendant race effect = <span class="math inline">\(8.5*\text{black defend}_c + .4*\text{black defend}_c*16.2\)</span><br>
Defendant race effect = <span class="math inline">\(15.2*\text{black defend}_c\)</span> (w/rounding error)</p>
<hr>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>plot_int <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(data<span class="sc">$</span>bias) <span class="sc">+</span> <span class="fu">sd</span>(data<span class="sc">$</span>bias), <span class="at">linewidth =</span> .<span class="dv">75</span>) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(data<span class="sc">$</span>bias) <span class="sc">-</span> <span class="fu">sd</span>(data<span class="sc">$</span>bias), <span class="at">linewidth =</span> .<span class="dv">75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="11_interactions_continuous_and_dichotomous_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="a-sample-brief-report-defendant-race-is-focal" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="a-sample-brief-report-defendant-race-is-focal"><span class="header-section-number">11.5</span> A sample brief report: Defendant race is focal</h2>
<p>Defendant guilt ratings were analyzed in a General Linear Model with defendant race (Black vs.&nbsp;White) as a dichotomous variable and juror implicit bias (mean centered) as a quantitative variable. The interaction between these two variables was also included in the model.</p>
<p>The overall model accounted for a significant amount of variance in guilt ratings, <span class="math inline">\(R^2= 0.59, F(3,236) = 114.00, p &lt; .001\)</span>. A significant main effect of defendant race was observed, 95% CI(<span class="math inline">\(b\)</span>)= [5.5,11.5], <span class="math inline">\(\Delta R^2=.06, t(236) = 5.66, p &lt; .001\)</span>, such that Black defendants were rated as 8.5 units more guilty than White defendants among jurors of mean bias. However, juror bias significantly moderated the defendant race effect, 95% CI(<span class="math inline">\(b\)</span>)= [0.2,0.6], <span class="math inline">\(\Delta R^2=.03, t(236) = 4.45, p &lt; .001\)</span>, indicating that the magnitude of the defendant race effect increased by 0.4 units for every one unit increase in juror bias (see Figure 1). Given this, the simple effect of defendant race was substantially reduced and non-significant among jurors who were low on bias (1 SD below the mean), 95% CI(<span class="math inline">\(b\)</span>)= [-2.4,5.6], <span class="math inline">\(\Delta R^2=.00, t(236)= 0.85, p= .399\)</span>. In contrast, the effect of defendant race was substantially larger and significant among jurors who were high on bias, 95% CI(<span class="math inline">\(b\)</span>)= [11.0,19.4], <span class="math inline">\(\Delta R^2=.09, t(236)= 7.15, p &lt; .001\)</span>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10_interactions_two_continuous.html" class="pagination-link" aria-label="Inferences about Two Continuous Predictors and their Interaction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inferences about Two Continuous Predictors and their Interaction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12_interactions_two_dichotomous.html" class="pagination-link" aria-label="Inferences about a Two Dichotomous Predictors and their Interaction">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferences about a Two Dichotomous Predictors and their Interaction</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jjcurtin/book_glm/edit/main/11_interactions_continuous_and_dichotomous.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>