project:
  type: book

execute:
  echo: true
  warning: true
  message: true
  freeze: auto

toc: true
toc-depth: 3
bibliography: refs.bib
css: book.css
callout-icon: false
code-fold: show

book:
  title: "Introduction to the General Linear Model"
  author: John J. Curtin, PhD
  site-url: https://github.io/jjcurtin/book_glm
  repo-url: https://github.com/jjcurtin/book_glm
  repo-branch: main
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - 01_overview.qmd
    - 02_sampling_distributions.qmd
    - 03_single_mean_shell.qmd
    - 04_single_quantitative_shell.qmd
    - 05_single_dichotomous_shell.qmd
    - 06_two_predictors_shell.qmd
    - 07_case_analysis_shell.qmd
    - 08_model_assumptions_shell.qmd
    - 09_transformations_shell.qmd
    - 10_interactions_two_quantitative_shell.qmd
    - 11_interactions_quantitative_and_dichotomous_shell.qmd
    - 12_interactions_two_dichotomous_shell.qmd
    - 13_categorical_variables_shell.qmd
    - 14_power_shell.qmd
    - 15_the_generalized_linear_model_shell.qmd
    - part: Appendices
      chapters:
        - app_terminology.qmd
        - repeated_measures.qmd
