project:
  type: book

execute:
  echo: true
  warning: true
  message: true
  freeze: auto

toc: true
toc-depth: 3
bibliography: refs.bib
css: book.css
callout-icon: false
code-fold: show

book:
  title: "Introduction to the General Linear Model"
  author: John J. Curtin, PhD
  site-url: https://github.io/jjcurtin/book_glm
  repo-url: https://github.com/jjcurtin/book_glm
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - web2_slide_decks.qmd
    - web3_required_readings.qmd
    - web4_application_assignments.qmd
    - web5_labs.qmd
    - web6_exams.qmd
    - web7_videos.qmd
    - part: Appendices
      chapters:
        - app1_exam_review.qmd
        - app2_terminology.qmd
        - app3_contrasts.qmd
        - app4_logistic_se.qmd