# Exam Concepts {.unnumbered}

## Exam 1

### Unit 1 - Overview

- What are the four levels of the General Linear model
- How do the number of $X$ variables differ across these levels?
- Number of $Y$ variables differ across these levels?
- Examples of special case analyses across these levels?


### Unit 2 - Sampling Distributions

- populations vs. samples
- parameters vs. parameter estimates
- What is sampling error?
- The logic and procedure for null hypothesis signficance testing
- Connecting NHST to sampling distributions
- Raw score distribitions vs. sampling distributions
- The Central Limit Theorem
- What is an unbiased estimator?
- What is the standard error for a parameter estimate and how does that connect to sampling distributions
- What factors affect the standard error of the mean
- How does the one-sample z-test connect sampling distributions and standard errors.
- What is the difference between the one-sample z-test and the one sample t-test


### Unit 3 - One parameter models

- What are the three uses of models
- What is the equation for a one parameter model for $Y_i$ and for $\hat{Y}_i$
- What is an error or residual in the context of a model. Define it in terms of $Y_i$ and $\hat{Y}_i$
- What are two reasonable methods for estimating total model error
- What are three important properties of parameter estimates?  Define each
- Why do we prefer the sum of squared errors over the sum of absolute errors?
- What is the  interpretation of $b_0$ if we estimate it by minimizing the sum of squared errors vs. the sum of absolute errors?
- Parameter estimates in our models miminize what?
- How do we use a t-test the null hypothesis that $b_0$ is zero in a one parameter model?  Connect this to the sampling distribution of $b_0$
- How do we use an F-test and model comparison to test the null hypothesis that $b_0$ is zero in a one parameter model?  How do we use sum of squared errors in this comparison? What is the compact and augmented model used to test the null about $b_0$ = 0.  How would you change these models if you had a null hypothesis about some value other than 0?
- What is a confidence interval for a parameter estimate?  Connect the confidence interval to the standard error of that parameter estimate
- How can we use a confidence interval to test the null hypothesis that $b_0$ (or any parameter estimate) is zero?
- The test of $b_0$ in a one parameter model is equivalent to what special case analysis?
- What is the formula for the t-test to test the null hypothesis that $b_0$ (or any parameter estimate) is zero? How would you modify this formula to test a null hypothesis about a value other than 0.


### Unit 4 - Two parameter models

- What is the equation for a two parameter model for $Y_i$ and for $\hat{Y}_i$
- What is the interpretation of $b_0$ and $b_1$ in a two parameter model?
- Identify $b_0$ and $b_1$ on a line plot of the data
- How are $b_0$ and $b_1$ estimated in a two parameter model?
- Compare the interpretation of $b_0$ in a one vs. two parameter model
- How do we test null hypotheses about $b_0$ and $b_1$ in a two parameter model using a t-test?  Connect this to the sampling distribution of $b_0$ and $b_1$A
- How do we test null hypotheses about $b_0$ and $b_1$ in a two parameter model using an F-test and model comparison?  What are the associated compact and augmented models for each test?
- What are the degrees of freedom equal to for the t-test and F-test
- What would the SSE be for two parameter model that perfectly predicts $Y$.  What would it be if there was no relationship between $X$ and $Y$?
- What is the impact of mean-centering $X$ on the interpretation of $b_0$ and $b_1$ in a two parameter model?
- What is the formula for the confidence interval for a parameter estimate in a two parameter model?  Connect the confidence interval to the standard error of that parameter estimate
- What is $R^2$ and how is it calculated in a two parameter model using SSE or using variances of $Y_i$, $\hat{Y}_i$, and $e_i$?
- What this the relationship between $R^2$ and $r_xy$ in the two parameter model?


### Unit 5 - One Dichotomous Predictor

- How do we handle dichotomous categorical variables in linear models?
- What are the two coding schemes we learned for coding regressors ($X$s) for dichtomous categorical predictors
- How do we interpret the parameter estimates for each coding scheme?
- How would values or interpretations of $b_0$ and $b_1$ change if we used other coding schemes (e.g., -1 vs. 1, 2 vs. 0)?
- What are the typical consequences of dichotomizing a quantitative predictor?  Should we generally do this or avoid it?
- How does the t-test or model comparison approach work for testing parameter estimates in a model with a dichotomous predictor?
- Identify $b_0$ and $b_1$ on a line plot of the data


### Unit 6 - Models with Two or More Predictors

- What is the equation for a model with two predictors for $Y_i$ and for $\hat{Y}_i$?  What is the general form for $k$ predictors?
- What is the interpretation of $b_0$, $b_1$, and $b_2$ in a model with two predictors?
- What are the five benefits of using multiple predictors in a model?
- What factors affect the standard error of a parameter estimate in a model with multiple predictors? (You do not need to know the exact formula for this but you do need to know all the components and the direction of their impact on the SE)
- What is $R^2_j$?
- What is the problem of multicolinearity?
- How do you identify if multicolinarity is a problem in a model?
- What are the appropriate compact and augmented models for testing any parameter estimate in a model with multiple predictors?
- What is the relationship between the SE for a parameter estimate and power to test the null hypothesis about that parameter estimate?  Connect this to your understanding of the sampling distribution for a parameter estimate
- What is the relationship between the SE for a parameter estimate and the precision of the parameter estimate?  Connect this to your understanding of the confidence interval and the sampling distribution for a parameter estimate. 
- What are the total, direct, and indirect/spurious effects of $X$s in a two predictor model?  How do you calculate each?  What models do you use to calculate each?
- What are the three variance based effect size estimates for models with two or more predictors?
  - Define them in terms of the variances of $Y_i$, $\hat{Y}_i$, and $e_i$
  - Define them in terms of sums of squares and models/model comparisons
  - What is the interpreation of each?
  - Link them to the areas of the Venn diagrams
  - Calculate them from sums of squares in Venn diagrams
  - How are they similar and different from each other?
  - When are each generally used?
- Identify $b_0$, $b_1$, and $b_2$ on a line plot of the data from a two predictor model with a dichotomous and quantitative predictor

## Exam 2

### Unit 7 - Case Analysis
- What is case analysis and why do we do it?
- What are the three primary characteristics of observations that we focus on in case analysis?
- When doing univariate and bivariate exploratory data analysis, what plots and summary statistics do we typically review; Which plots are good for which types of variables?
- Leverage
  - What is it
  - What metric do we use to identify points with high leverage
  - What is the impact of leverage on our models?
- Regression Outliers
  - What are they?
  - What three metrics do we use to identify regression outliers and which one do we prefer?
  - What are the two potential impacts of regression outliers on our models?
- Influential Observartions
  - What are they?
  - What metrics do we use to identify influential observations and how are they different from each other?
  - What is an added variable plot? What do we plot on the x and y axes this plot?
  - What are the two potential impacts of influential observations on our models?
- Identify points with high leverage, regression outliers, and influential points on a scatterplot?
- What is the Covratio?
- What are three options for how to handle regression outliers and influential points?

### Unit 8 - Model Assumptions

- What are the five assumptions of the general linear model?
- What are the consequences of violating each assumption?
- What are the implications of the unreliable X assumption for the use of covariates?
- What is a quantile-quantile (quantile comparison) plot and what do we use it for?
- What is a spread-location plot and what do we use it for?
- What options exist to address problems with non-constant (heterogeneity) variance of residuals?
- What is a Component + Residual plot and what do we use it for?  What do we plot on the x and y axes of this plot?

### Unit 9 - Transformations

- What are power transformations and why do we use them?
- What are the benefits of the Box-Cox transformation vs. a simple power transformation?
- What happens to scores as we ascend and descend the ladder of power transformations?
- What is a start and when do we need to use one (two uses)?
- How can we use power transformations to address skewed residuals?
- How can we use power transformations to address non-constant variance of residuals?
- Is it more common to transform y or x to adddress skew and non-constant variance problems?  What about linearity problems (when y and when)
- What type of lineary problems can power transformations address and what types can it not fix?
- What is the Mosteller and Tukey’s bulging rule? What transformations do we use for linearity issues in each quadrant?





### Unit 10-12 - Interactions

- What is an interaction? 
- How do you create a regressor to test for an interaction between predictors?
- How do you interpret the parameter estimates for a model with an interaction between two predictors? How does this change if the predictors are both quant, both dichotomous, or one of each?
- Which parameter estimates will change (and which won't) as you change the scaling of $X$s in a model with an interaction.
- How can you use the model formula (with parameter estimates) to describe how the magnitude of the effect of one X will change depending on a second X?  Again, know how to do this for models with two quant predictors, two dichotomous predictors, and one of each.
- Calculate how any parameter estimate in a model will change if a specific $X$ was re-scaled in some way (e.g., mean centered or centered on some other value).  Know this for both quant predictors and dichotomous predictors.
- When do you mean center a quant $X$ in an interactive model When do you center on some value other than the mean
- When do you use centered (contrast) codes vs. dummy codes for a dichotomous $X$ in an interactive model? 
- Link parameter estimates from an interactive  model to a plot of the model.  Know how to do this for models with two quant predictors, two dichotomous predictors, and one of each.
- What are main an simple effects in a model with an interaction?  How do you obtain them?  How do you  interpret them?  How is this different for models with two quant predictors, two dichotomous predictors, and one of each?
- How do you test for an interaction using a t-test or model comparison?  How do you test for main and simple effects in these models?
- what is a cell mean, marginal mean, and grand mean in a model with two dichotomous predictors?
- Link the parameter estimates from an interactive model with two dichotomous predictors to table of means.   Be able to go both directions such that you could write out the model formula (including parameter estimates) for a model from a table of means either when using centered (contrast) codes or dummy codes.
- Quantify the magnitude of main effects, simple effects and an interaction between two dichotomous predictors using a table of means.


### Unit 13 - Categorical Predictors with More than Two Levels

- Why can we not simple assign sequential numbers to levels of a categorical predictor?
- How do you calculate dummy coded regressors for categorical variables with 3 or more levels (including what codes are assigned to each regressor)?
- How do you interpret the parameter estimates for dummy coded regressors?
- How do you calculate contrast coded regressors for categorical variables with 3 or more levels (including what codes are assigned to each regressor)?  Know how to do this for 3 and 4 level categorical variables given a description of the planned contrasts.
- How do you interpret the parameter estimates for contrast coded regressors?
- Be able to calculate predicted means for any level given a model formula that used either dummy or contrast codes
- Why are pairwise contrasts using dummy coded regressors in a linear model superior to pairwise t-tests using between subjects/two group t-tests?
- How can you get the test of the third pairwise contrast when using dummy coded regressors for a 3 level categorical predictor?
- What is the value of testing for a main effect of a categorical variable?  When will you do this?
- What model comparison will provide a test of the main effect of a categorical predictor when other predictors are also in the model
- When will $\Delta R^2$ sum to the full $R^2$ for a model with a categorical predictor?  When will they not?
- What is test-wise and family-wise error rates?  
- When and how do we protect against inflation of family-wise Type I error rates when doing multiple comparisons among levels of a categorical predictor?  How is this similar or different when using planned orthogonal contrasts vs. planned pairwise conntrasts vs. unplanned contrasts?
- How and when should we use Fisher LSD approach
- How and when should we use Holm-Bonferroni approach
- How is the Holm-Bonferroni approach superior to the Bonferroni approach?
- How and when should we use Scheffe test approach
- What is the Bonferroni inequality

### Unit 14 - The Generalized Linear Model

- When might you use the generalized linear model?
  - When would you specifically use a generalized linear model with the logit link function and binomial distribution?  What special case analysis is this?
  - When would you use a generalized linear model with the log link function and poisson distribution?  
- Be able to calculate odds or probability from the other.  Be able to calculate log-odds from a model.
- What is an odds ratio and how do you interpret it for a quantitative predictor or regressor for a categorical predictor?
- What do we use the odds ratio as the preferred effect size in logistic regression?
- Be able to compare two simple (one X) logistic plots (in probability units) and tell which has bigger/smaller $b_0$ and $b_1$ 
- What are the three approaches to testing parameter estimates in logistic regression? Which is preferred and why?
- How do we handle categorical predictors and multiple predictors in logistic regression?

### Unit 15 - Power Analysis and Statistical Validity

- Understand the confusion matrix and its use with talking about statistical validity.  Be able to label the four cells of the confusion matrix.
- What the difference between Type I and Type II errors?
- What are the factors that affect power in the linear model?  How do they affect power? Be able to discuss these relationships with respect to the sampling distribution for a parameter estimate
- What are the two approaches to power analyses.  When and why do you do each of them
- What problems are associated with low power studies?
- What is positive predictive value and why does it matter?
- Why are sample effect size estimates often incorrect (too large) when calculated in studies with low power
- What is the problem of vibration of effects?
- What is publication bias and why is it worse for low power studies?
- What are the 7 important study characteristics that should be pre-registered?

