# Course Syllabus {.unnumbered}

## Course Designations And Attributes

- **Course Website**: [https://jjcurtin.github.io/book_glm/](https://jjcurtin.github.io/book_glm/)
- **Credits**: 4
- **Level**: Advanced
- **Breadth**: Social Science
- **L&S** Credit Type: Counts as LAS credit (L&S)
- **Instructional** Mode: All face-to-face
- **How Credit Hours are met by the Course**: Four and ½ hours of classroom or direct faculty/instructor instruction and a minimum of eight hours of out of class student work each week over approximately 14 weeks.
- **Requisites**: None

## Meeting Time And Location

- **Lecture**: Monday and Wednesday, 2:30-3:45 pm; Psychology 103 
- **Labs**: 
  - Friday 9:00-11:00 am (section 301, room 228; Punturieri) 
  - Friday 1:30-3:30 pm  (section 302, room 228; Yu) 
  - Friday 9:00-11:00 am (section 303, room 311i; Dong)

## Instructor

- John J. Curtin, Ph.D.
- Office hours: Room 326, Wednesdays, 3:45 - 4:45 pm or by appt. 

## Teaching Assistants

- LiChen Dong; Office hours: Room 626, Mondays, 11 - 12 pm 
- Claire Punturieri; Office hours:  Room 325, Tuesdays, 8:30 - 9:30 am
- Coco Yu; Office hours: Room 325, Tuesdays, 1 - 2 pm

## Communications
All course communications will occur in the course’s Slack workspace.  You should have received an invitation to join the workspace.  If you have difficulty joining, please let me know immediately.  The TAs and I will respond to all Slack messages within 1 business day (and often much quicker).  Please plan accordingly (e.g., weekend messages may not receive a response until Monday).  For general questions about class, coding assignments, etc., please post the question to the appropriate public channel.  If you have the question, you are probably not alone.  For issues relevant only to you (e.g., class absences, accommodations, etc.), you can send a direct message in Slack to me and the TAs.  If you DM only me, I will share the DM with the TAs unless you request otherwise. Therefore, it is generally best if you include all three TAs on the DM when you start the thread.  In general, we prefer that all course communication occur within Slack rather than by email so that it is centralized in one location.   

## Course Description 
One-sample t-test, independent-samples t-test, simple and multiple regression, effect size indicators, analysis of variance (ANOVA), analysis of covariance (ANCOVA), case analysis, model assumptions, transformations, and the generalized linear model 

## Course Goals 
The goal of this course is to familiarize you with a statistical data analysis procedure called the general linear model. We will spend most of the semester on the use of the general linear model as a tool for analyzing data from psychological experiments. We will give special attention to the interpretation of model parameter estimates, models with quantitative and categorical predictors, and the interpretation of interaction effects in the general linear model. We will be using the statistics software R (http://www.r-project.org/). Please know that extensive work outside the classroom is required in order to succeed in this class. You are encouraged to participate actively in the class, both the lecture and the lab session.

## Course Learning Outcomes

By the end of the course, the students should master the following data-analytic techniques and skills:

- Inferences about a single mean (t-test)
- The analysis of single and multiple dichotomous/categorical predictors
- The analysis of single and multiple quantitative predictors
- The analysis of interactions among predictors
- The analysis of contrasts among levels of categorical predictors
- The use of centering predictors in interactive models
- Assessment and remediation techniques for case analysis and model assumptions
- Logistic regression as exemplar of the generalized linear model
- Generating publication-level graphs

## Course Requirements And Grades

Course requirements include regular attendance, active participation in class discussion, and completion of all exams and application assignments. 

There will be two closed-book concepts exams completed in class to assess conceptual knowledge and three application exams completed outside of class to assess your ability to implement your conceptual knowledge with real data (each of these 5 exams counts for 15% of your total grade). The first concepts exam  is scheduled for the week of 10/21 (Mon or Wed TBD).  The second concepts exam is scheduled during the exam period on Wednesday, December 18 from 8:15 - 9:45 am (room TBD). Please plan your end of semester travel accordingly. The application exams will be assigned at the end of weeks 5, 10, and 15.  Those weeeks begin on  9/30, 11/4, & 12/9, respectively.

There will also be approximately weekly application assignments, which will involve hands-on application of the material similar to (but shorter than) the application exams. They are assigned Wednesdays at 3:45 pm and are due the following Wednesday at 1:30 pm. These application assignments are graded on a pass/fail basis, and together constitute 20% of your total grade. 

Finally, 5% of your grade will be determined by your attendance and participation in lecture and lab.

Final letter grades are based on total course percentages as follows: 

- A: 93 or above 
- AB: 88 - 92 
- B: 83 - 87
- BC: 78 - 82
- C: 70 - 77
- D: 60-69
- F: < 60

## Required Texts
Judd, C.M., McClelland, G. H., & Ryan, C. (2017). Data Analysis: A Model-
Comparison Approach. 3rd Edition. New York, US: Routledge. ISBN: 9780805833881.

## Additional Required Readings
Additional required readings will be provided as pdfs on the course website. The readings are pulled from various texts and primary sources. Supplemental readings and recommended reference texts are also provided on the course website and the end of this document. You are expected to read only the required readings. You will not be tested on the other readings.

## Required Software
This course will contain a significant applied component. As such, access to statistical analysis software is required. In the context of this course, we will rely heavily on [R](http://www.r-project.org/). R is freely available and is rapidly becoming the standard for statistical analysis in many disciplines. 

A secondary goal of the course will be to provide you with introductory data wrangling skills in R within the [Tidyverse](https://www.tidyverse.org/) ecosystem of packages. The Tidyverse is "an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures." It is arguably the dominant approach for data science in R today.

## Course Schedule
This schedule is provisional so that we may adjust our rate of progress as necessary to ensure maximal mastery of the material. See course website for the most up to date version of the assigned readings and topics.

1) Introduction to inferential statistics (1 day)
- introduction to the course
- the GLM framework
- data exploration in R (descriptive statistics, visual displays) (lab only)

2) Sampling Distributions (1 day)
- standard deviation, standard error of the mean
- theory of null hypothesis significance testing

3) Inferences about a single mean (one-sample t test) (1 day)
- the null model ($Y = b_{0}$)
- sum of squares, number of estimated parameters, residuals, etc.
- the basic model ($Y = b_{0}$)
- statistical inference (comparison of basic model with null model, computation of t, interpretation of p)
- writing up the results (text, graphs, tables) of a one-sample t test

4) Inferences about a single quantitative predictor (simple regression) (2 days)
- the model : $Y = b_0 + b_{1}X_{1}$ when $X_{1}$ is quantitative
- computation of residuals, meaning of residuals
- graphic representation: intercept, slope, residuals
- statistical inference (comparison of the new model with the basic model, computation of t and F, interpretation of p)
- proportion of variance explained, computation of $R^{2}$, interpretation of $R^{2}$, effect sizes
- running a simple regression in R and interpreting the R output
- writing up the results (text, graphs, tables) of a simple regression analysis

5) Inferences about a single dichotomous predictor (independent-samples t test) (1 day)
- the model: $Y = b_{0} + b_{1}X_{1}$ when $X_{1}$ is dichotomous
- computation of residuals, meaning of residuals (= within-group variance)
- graphic representation: intercept, slope, residuals; comparison with bar graph
- statistical inference (comparison of the new model with the basic model, computation of t and F, interpretation of p)
- running an independent-samples t test in R (using the `lm()` function in R) and interpreting the R output
- writing up the results (text, graphs, tables) of an independent-samples t test

6) Inferences about two (or more) predictors (multiple regression without interaction) (4 days)
- the model: $Y = b_{0} + b_{1}X_{1} + b_{2}X_{2}$ when $X_{1}$ is dichotomous and $X_{2}$ is quantitative
- the model: $Y = b_{0} + b_{1}X_{1} + b_{2}X_{2}$ when $X_{1}$ and $X_{2}$ are both quantitative
- computation of residuals, meaning of residuals
- graphic representation: two lines, intercepts, slopes, residuals
- statistical inference (model comparison, interpretation of the effect of one variable on DV while controlling for the effects of another variable)
- computation of partial r, interpretation of partial r
- different theoretical predictions that can be answered by multiple regression analyses that do not contain interactions
- models with 3, 4, 5, etc. predictors
- issues of collinearity, variance inflation, tolerance
- data fishing, overfitting, hierarchical vs. stepwise vs. simultaneous models
- raw vs. standardized coefficients, partial r
- writing up the results of a multiple regression analysis

7)  Dealing with messy data I – case analysis (1 day)
- the different ways of being an outlier
- outlier statistics: levers $h_{ij}$, studentized deleted residuals, Cook's D
- dealing with outliers

8)  Dealing with messy data II – model assumptions (1 day)
- the 5 assumptions of the GLM: exact X, independence, normality, constant variance, and linearity
- data exploration in R (visual displays: residual plots, normal quantile plots, density plots, spread-level plots, etc.)
- statistical indicators: ncv test, gvlma test
- first remedies: heteroscedasticity-corrected standard errors, weighted least squares

9)  Dealing with messy data III – transformations (1 day)
- How to address violations of GLM model assumptions: power transformations, root transformations, how to find the best transformations
- how to analyze proportions and correlations as data

10) Inferences about two predictors and their interaction (= moderation) (1 day)
- centering variables: mean deviation form, contrast codes
- the model: $Y = b_{0} + b_{1}X_{1}c + b_{2}X_{2}c + b_{3}(X_{1}c * X_{2}c$) when $X_{1}$ is dichotomous, $X_{2}$ is quantitative and both predictors are centered]
- graphic representation: different slopes for different folks, $b_{3}$ tests the difference between the two slopes
- what happens if variables are not centered?
- interpretation of an interaction
- writing up the results of a multiple regression analysis with an interaction

11)  Inferences about two quantitative predictors and their interaction (1 day)
- the model: $Y = b_{0} + b_{1}X_{1}c + b_{2}X_{2}c + b_{3}(X_{1}c * X_{2}c$) when $X_{1}$ and $X_{2}$ are both quantitative
- interpretation of an interaction between two quantitative predictors
- the pitfalls of dichotomization II: imaginary interaction effects

12)  Inferences about two dichotomous predictors and their interaction (= 2 x 2 ANOVA) (1 day)
- the model: $Y = b_{0} + b_{1}X_{1}c + b_{2}X_{2}c + b_{3}(X_{1}c * X_{2}c$) when $X_{1}$ and $X_{2}$ are both dichotomous
- difference between main effects and simple effects
- interpretation of interactions in 2 x 2 ANOVAs (Rosnow & Rosenthal)
- comparison of the GLM terminology and the ANOVA terminology
- the pitfalls of dichotomization I: loss of power, biased estimates
- writing up the results of a 2 x 2 ANOVA

13)  Inferences about three predictors and one interaction (= ANCOVA) (1 day)
- the model: $Y = b_{0} + b_{1}X_{1}c + b_{2}X_{2}c + b_{3}(X_{1}c * X_{2}c) + b_{4}X_{3}$ when $X_{1}$ and $X_{2}$ are both dichotomous and $X_{3}$ is quantitative
- interpretation of $b_{3}$
- generalization to other models (e.g., the covariate is dichotomous, one of the predictors is quantitative)
- appropriate and "inappropriate" uses of ANCOVA
- writing up the results of an ANCOVA

14) Statistical power and power analysis (2 day)
- type I and type II errors
- factors determining statistical power
- how to compute power
- positive predictive value 
- Readings: Button et al. (2013). Cohen (1992). 

15) Inferences about categorical predictors with three or more levels (2 days)
- orthogonal and non-orthogonal contrasts
- comparing several experimental groups to one reference group (dummy codes)
- test-wise error rate vs. family-wise error rate
- Fisher LSD Protected Testing for two or three planned comparisons
- Holm-Bonferroni Adjustment for four or more planned comparisons
- Scheffé Approach for unplanned comparisons
- Readings: Abelson & Prentice (1997). Guggenmos et al. (2018).

## Recommended General Texts For Data Analysis And Research Methodology
- Abelson, R. P. (1995). Statistics as Principled Argument. Hillsdale, NJ: Lawrence Erlbaum Associates.
- Aiken, L. S., & West, S. G. (1991). Multiple Regression: Testing and Interpreting Interactions. Newbury Park, CA.: Sage.
- Chambers, J (2008). Software for Data Analysis: Programming with R. New York: Springer Science Business Media.
- Cook, T. D., & Campbell, D. T. (1979). Quasi-Experimentation - Design and Analysis Issues for Field Settings. Boston, MA: Houghton Mifflin Company.
- Cohen, J., Cohen, P., West, S. G., & Aiken,, L. S. (2003). Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences (3rd. Ed.). Mahwah, NJ: Lawrence Erlbaum Associates.
- Dalgaard, P. (2008) Introductory Statistics with R (2nd edition). New York: Springer Science Business Media.
- Fox, J. (2015). Applied Regression, Generalized Linear Models, and Related Methods, Third Edition. Sage Publications.
- Fox, J., & Weisberg, S. (2010). An R Companion to Applied Regression (3rd Edition). Sage Publications.
- Hayes, A. F. (2013). Introduction to mediation, moderation, and conditional process analysis; A regression-based approach (3rd edition). NY, US: Guilford Press.
- Healy, K. (2019). Data Visualization A Practical Introduction. Princeton, NJ: Princeton University Press
- Hoyle, R. H., Harris, M. J., & Judd, C. M. (2006). Research Methods in Social Relations (8th edition). Belmont, CA, US: Allyn & Bacon.
- Judd, C. M., & Kenny, D. A. (1981). Estimating the Effects of Social Interventions. New York, NY: Cambridge University Press.
- Kline, R. B. (2016). Principles and practice of structural equation modeling (5th edition). New York, US: The Guilford Press
- Kutner, M., Nachtscheim, C., & Neter, J (2004). Applied Linear Regression Models, Fourth edition, McGraw-Hill.
- Raudenbush, S. W., & Bryk, A. S. (2002). Hierarchical Linear Models. Applications and Data Analysis Methods (2nd ed.). Newbury Park, CA: Sage.
- Reis, H. T., & Judd, C. M. (2014). Handbook of Research Methods in Social and Personality Social Psychology (2nd ed.). New York, NY: Cambridge University Press.
- Snijders, T. A. B., & Bosker, R. J. (2012). Multilevel Analysis: An Introduction to Basic and Advanced Multilevel Modeling (2nd ed.). London, UK: Sage Publishers.
- Tabachnick, B. G., & Fidell, L. S. (2018). Using Multivariate Statistics (7th edition). New York, NY: Pearson.
- Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data (2nd edition). Sebastopol, CA: O’Reilly Media

## Ethics of Being a Student in the Department of Psychology
The members of the faculty of the Department of Psychology at UW-Madison uphold the highest ethical standards of teaching and research. They expect their students to uphold the same standards of ethical conduct. By registering for this course, you are implicitly agreeing to conduct yourself with the utmost integrity throughout the semester. In the Department of Psychology, acts of academic misconduct are taken very seriously. Such acts diminish the educational experience for all involved – students who commit the acts, classmates who would never consider engaging in such behaviors, and instructors. Academic misconduct includes, but is not limited to, cheating on assignments and exams, stealing exams, sabotaging the work of classmates, submitting fraudulent data, plagiarizing the work of classmates or published and/or online sources, acquiring previously written papers and submitting them (altered or unaltered) for course assignments, collaborating with classmates when such collaboration is not authorized, and assisting fellow students in acts of misconduct. Students who have knowledge that classmates have engaged in academic misconduct should report this to the instructor.

## Academic Integrity
By enrolling in this course, each student assumes the responsibilities of an active participant in UW-Madison’s community of scholars in which everyone’s academic work and behavior are held to the highest academic integrity standards. Academic misconduct compromises the integrity of the university. Cheating, fabrication, plagiarism, unauthorized collaboration, and helping others commit these acts are examples of academic misconduct, which can result in disciplinary action. This includes but is not limited to failure on the assignment/course, disciplinary probation, or suspension. Substantial or repeated cases of misconduct will be forwarded to the Office of Student Conduct & Community Standards for additional review. For more information, refer to [https://conduct.students.wisc.edu/academic-misconduct/](https://conduct.students.wisc.edu/academic-misconduct/)

## ChatGPT and other LLMs
I suspect you have all seen discussions of all that ChatGPT and other LLMs can do by now and their impact on teaching and assessment.  I believe that AI like ChatGPT will eventually become an incredible tool for data scientists and programmers.  As such, I view these advances with excitement.  Of course, I don't plan to assign a grade to ChatGPT so I want to make sure that we are clear on when you can and when you cannot use it.   

Given that I expect AI like ChatGPT and other LLMs to become a useful tool in our workflow as  professionals, now is the time to start to learn how they can help.  Therefore, you are free to use them for coding assistance during any of our **application assignments** AND the **application exams**.  Code from ChatGPT is unlikely to be sufficient in either context (and my testing suggests it can be flat out wrong in some instances!) but I suspect that it will still be useful.  

In contrast, you **cannot** use ChatGPT or other LLMs/AI to answer the conceptual questions on the conceptual exams.   Those questions are designed to assess your working knowledge about concepts and best practices.  That information must be in YOUR head and I want to be 100% clear that use of ChatGPT/AI (or any other sources other than what is in your head) to answer those questions will be considered cheating and handled as such if detected.  There will be a zero tolerance policy for such cheating and it will be considered academic misconduct and disciplined as such. 
## Accommodations Policies
McBurney Disability Resource Center syllabus statement: “The University of Wisconsin- Madison supports the right of all enrolled students to a full and equal educational opportunity. The Americans with Disabilities Act (ADA), Wisconsin State Statute (36.12), and UW-Madison policy (Faculty Document 1071) require that students with disabilities be reasonably accommodated in instruction and campus life. Reasonable accommodations for students with disabilities is a shared faculty and student responsibility. Students are expected to inform faculty [me] of their need for instructional accommodations by the end of the third week of the semester, or as soon as possible after a disability has been incurred or recognized. Faculty [I], will work either directly with the student [you] or in coordination with the McBurney Center to identify and provide reasonable instructional accommodations. Disability information, including instructional accommodations as part of a student's educational record, is confidential and protected under FERPA.” [http://mcburney.wisc.edu/facstaffother/faculty/syllabus.php](http://mcburney.wisc.edu/facstaffother/faculty/syllabus.php) 

UW-Madison students who have experienced sexual misconduct (which can include sexual harassment, sexual assault, dating violence and/or stalking) also have the right to request academic accommodations. This right is afforded them under Federal legislation (Title IX). Information about services and resources (including information about how to request accommodations) is available through Survivor Services, a part of University Health Services: [https://www.uhs.wisc.edu/survivor-services/](https://www.uhs.wisc.edu/survivor-services/).

## Diversity & Inclusion
Institutional statement on diversity: “Diversity is a source of strength, creativity, and innovation for UW-Madison. We value the contributions of each person and respect the profound ways their identity, culture, background, experience, status, abilities, and opinion enrich the university community. We commit ourselves to the pursuit of excellence in teaching, research, outreach, and diversity as inextricably linked goals.

The University of Wisconsin-Madison fulfills its public mission by creating a welcoming and inclusive community for people from every background – people who as students, faculty, and staff serve Wisconsin and the world.” [https://diversity.wisc.edu/](https://diversity.wisc.edu/)

## Complaints
Occasionally, a student may have a complaint about a TA or course instructor. If that happens, you should feel free to discuss the matter directly with the TA or instructor. If the complaint is about the TA and you do not feel comfortable discussing it with the individual, you should discuss it with the course instructor. Complaints about mistakes in grading should be resolved with the TA and/or instructor in the great majority of cases. If the complaint is about the instructor (other than ordinary grading questions) and you do not feel comfortable discussing it with the individual, make an appointment to speak to the Associate Chair for Graduate Studies, Professor Shawn Green, cshawn.green@wisc.edu. If you have concerns about climate or bias in this class, or if you wish to report an incident of bias or hate that has occurred in class, you may contact the Chair of the Department, Professor Allyson Bennett (allyson.j.bennett@wisc.edu) or the Chair of the Psychology Department Climate & Diversity Committee, Martha Alibali (martha.alibali@wisc.edu). You may also use the University’s bias incident reporting system, which you can reach at the following link: [https://doso.students.wisc.edu/services/bias-reporting-process/](https://doso.students.wisc.edu/services/bias-reporting-process/).

## Concerns About Sexual Misconduct
All students deserve to be safe and respected at UW-Madison. Unfortunately, we know that sexual and relationship violence do happen here. Free, confidential resources are available on and off campus for students impacted by sexual assault, sexual harassment, dating violence, and stalking (regardless of when the violence occurred). You don’t have to label your experience to seek help. Friends of survivors can reach out for support too. A list of resources can be found at [https://www.uhs.wisc.edu/survivor-resources/](https://www.uhs.wisc.edu/survivor-resources/) If you wish to speak to someone in the Department of Psychology about your concerns, you may contact the Chair of the Department, Professor Allyson Bennett (allyson.j.bennett@wisc.edu) or the Associate Chair of Graduate Studies, Professor Shawn Green (cshawn.green@wisc.edu). Please note that all of these individuals are Responsible Employees ([https://compliance.wisc.edu/titleix/mandatory-reporting/#responsible-employees)](https://compliance.wisc.edu/titleix/mandatory-reporting/#responsible-employees).
