# Application Assignments {.unnumbered}

## Week 01: Due Friday, 9/12 at 8:30 am

- [instructions](/homework/week_01/hw_01.pdf) 
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_01_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_01_key.qmd)

## Week 02: Due Friday, 09/19 at 8:30 am

- [shell](homework/week_02/hw_02_shell.qmd)
- [data](homework/data/hw_02_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_02_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_02_key.qmd)

## Week 03: Due Friday, 09/26 at 8:30 am

- [ggplot cheatsheet](/homework/week_03/ggplot2_cheatsheet.pdf)
- [shell](/homework/week_03/hw_03_shell.qmd)
- [data](/homework/data/hw_03_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_03_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_03_key.qmd)

## Week 04: Due Friday, 10/03 at 8:30 am

- [shell](/homework/week_04/hw_04_shell.qmd)
- [data](/homework/data/hw_04_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_04_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_04_key.qmd)

## Week 05: No application assignment.  Application exam week!

## Week 06: Due Friday, 10/17 at 8:30 am

- [shell](/homework/week_06/hw_06_shell.qmd)
- [data](/homework/data/hw_06_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_06_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_06_key.qmd)

## Week 07: Due Friday, 10/24 at 8:30 am

- [shell](/homework/week_07/hw_07_shell.qmd)
- [iq data](/homework/data/hw_07_iq)
- [brain data](/homework/data/hw_07_brain)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_07_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_07_key.qmd)

## Week 08: Due Friday, 10/31 at 8:30 am

No homework this week. Happy Halloween!

## Week 09: Due Friday, 11/07 at 8:30 am

- [shell](/homework/week_09/hw_09_shell.qmd)
- [data](/homework/data/hw_09_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_09_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_09_key.qmd)

## Week 10: No application assignnment.  Application exam week!

## Week 11: Due Friday, 11/21 at 8:30 am

- [shell](/homework/week_11/hw_11_shell.qmd)
- [data](/homework/data/hw_11_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_11_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_11_key.qmd)

## Week 12: Due Friday 11/28 at 8:30 am

- [shell](/homework/week_12/hw_12_shell.qmd)
- [data](/homework/data/hw_12_data.csv)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_12_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_12_key.qmd)

## Week 13: No application assignment.  Thanksgiving Break

## Week 14: Due Friday 12/12 at 8:30 am

- [shell](/homework/week_14/hw_14_shell.qmd)
- [data1](/homework/data/hw_14_interactions.csv)
- [data2](/homework/data/hw_14_three_level.dat)
- key: [html](https://dionysus.psych.wisc.edu/610/homework/hw_14_key.html); [qmd](https://dionysus.psych.wisc.edu/610/homework/hw_14_key.qmd)

## Week 15: No application assignment.  Application exam week!
