# Lab Materials {.unnumbered}


## Week 1: 09/05

- [Installing R, R Studio, & Quarto](/lab/install_notes.pdf)
- [Student shell](/lab/week_01/lab_01_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_01_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_01_ta.html)

## Week 2: 09/12

- [Lab 02 data](/lab/data/lab_02_data.csv)
- [Student shell](/lab/week_02/lab_02_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_02_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_02_ta.html)

## Week 3: 09/19

- [Lab 03 data](/lab/data/lab_03_data.csv)
- [Student shell](/lab/week_03/lab_03_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_03_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_03_ta.html)

## Week 4: 09/26

- [Lab 04 quantitative data](/lab/data/lab_04_data_cont.csv)
- [Lab 04 dichotomous data](/lab/data/lab_04_data_dich.xlsx)
- [Student shell](/lab/week_04/lab_04_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_04_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_04_ta.html)
- [Video recording of lab](https://mediaspace.wisc.edu/media/lab_04_claire/1_l1mfwvlq)

## Week 5: 10/03
- No data file (using built-in data from R)
- [Student shell](/lab/week_05/lab_05_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_05_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_05_ta.html)
- [Video recording of lab](https://mediaspace.wisc.edu/media/lab_05_claire/1_i06aljoy)

## Week 6: 10/10
- [data](/lab/data/lab_06_graphing.csv)
- [Student shell](/lab/week_06/lab_06_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_06_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_06_ta.html)

## Week 7: 10/17
- [data](/lab/data/lab_07_data.csv)
- [Student shell](/lab/week_07/lab_07_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_07_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_07_ta.html)

## Week 8: 10/24
- [data](/lab/data/lab_08_data.csv)
- [Student shell](/lab/week_08/lab_08_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_08_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_08_ta.html)

## Week 9: 10/31
- [data](/lab/data/lab_09_data.csv)
- [Student shell](/lab/week_09/lab_09_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_09_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_09_ta.html)

## Week 10: 11/07

- [data](/lab/data/lab_10_data.csv)
- [Student shell](/lab/week_10/lab_10_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_10_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_10_ta.html)

## Week 11: 11/14

- [data](/lab/data/lab_11_data.csv)
- [Student shell](/lab/week_11/lab_11_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_11_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_11_ta.html)

## Week 12: 11/21

- [Student shell](/lab/week_12/lab_12_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_12_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_12_ta.html)

## Week 14: 12/5

- [data](/lab/data/lab_14_data.csv)
- [Student shell](/lab/week_14/lab_14_shell.qmd)
- TA notebook: [qmd](https://dionysus.psych.wisc.edu/610/lab/lab_14_ta.qmd); [html](https://dionysus.psych.wisc.edu/610/lab/lab_14_ta.html)