{
  "hash": "239502153053a8135444be73c8a029ab",
  "result": {
    "engine": "knitr",
    "markdown": "--- \noutput: html_document \neditor_options:  \n  chunk_output_type: console\n--- \n\n\n\n \n# Sampling Distributions, Parameters, and Parameter Estimates \n\n-----\n\n## Inferential Statistics\n\nInferential statistics are used to estimate *parameters* in the population from parameter estimates in a sample drawn from that population. \n\\\n\\\nIn inferential statistics, we use these parameter estimates to test hypotheses (predictions; null and alternative hypotheses) about the size of the population parameter. \n\\\n\\\nThese predictions about the size of population parameters typically map directly onto research questions about (causal) relationships between variables (IVs and DV).\n\\\n\\\nAnswers from inferential statistics are **probabilistic**. In other words, all answers have the potential to be wrong and you will provide an index of that probability along with your results. \n\n-----\n\n## Populations\n\nA population is any clearly defined set of objects or events (people, occurrences, animals, etc.). Populations usually represent all events in a particular class (e.g., all college students, all alcoholics, all depressed people, all people). It is often an abstract concept because in many/most instances you will never have access to the entire population.\n\\\n\\\nFor example, many of our studies may have the population of all people as its target.\n\\\n\\\nNonetheless, researchers usually want to describe or draw conclusions about populations (e.g., We don't care if some new drug is an effective treatment for 100 people in your sample. Will it work, on average, for everyone we might treat?). \n\n-----\n\n## (Population) Parameters\n\nA parameter is a value used to describe a certain characteristic of a population. It is usually unknown and therefore has to be estimated.\n\\\n\\\nFor example, the population mean is a parameter that is often used to indicate the average/typical value of a variable in the population.\n\\\n\\\nWithin a population, a parameter is a fixed value which does not vary within the population at the time of measurement (e.g., the mean height of people in the US at the present moment).\n\\\n\\\nYou typically can't calculate these parameters directly because you don't have access to the entire population.\n\\\n\\\nWe use Greek letters to represent population parameters ($\\mu$, $\\sigma$, $\\sigma^2$, $\\beta_0$, $\\beta_j$).\n\n-----\n\n## Samples & Parameter Estimates\n\nA sample is a finite group of units (e.g., participants) selected from the population of interest.\n\\\n\\\nA sample is generally selected for a study because the population is too large to study in its entirety. We typically have only one sample in a study.\n\\\n\\\nWe use the sample to estimate and test parameters in the population. \n\\\n\\\nThese estimates are called parameter estimates.\n\\\n\\\nWe use Roman letters to represent sample parameter estimates ($\\overline{X}$, $s$, $s^2$, $b_0$, $b_j$).\n\n-----\n\n## Sampling Error\n\nSince a sample does not include all members of the population, parameter estimates generally differ from parameters on the entire population (e.g., use mean height of a sample of 1000 people to estimate mean height of US population).\n\\\n\\\nThe difference between the (sample) parameter estimate and the (population) parameter is sampling error.\n\\\n\\\nYou will not be able to calculate the sampling error of your parameter estimate directly because you don't know the value of the population parameter. However, you can estimate it by probabilistic modeling of the *hypothetical sampling distibution* for that parameter.\n\n-----\n\n## Hypothetical Sampling Distribution\n\nA sampling distribution is a probability distribution for a parameter estimate drawn from all possible samples of size $N$ taken from a population.\n\\\n\\\nA sampling distribution can be formed for any population parameter.\n\\\n\\\nEach time you draw a sample of size $N$ from a population you can calculate an estimate of that population parameter from that sample.\n\\\n\\\nBecause of sampling error, these parameter estimates will not exactly equal the population parameter. They will not equal each other either. They will form a distribution.\n\\\n\\\nA sampling distribution, like a population, is an abstract concept that represents the outcome of repeated (infinite) sampling. You will typically only have one sample.\n\n-----\n\n## What if we didn't need samples?\n\n***Research question:*** How do inhabitants of a remote pacific island feel about the ocean? Population size = 10,000.\n\\\n\\\n***Dependent measure:*** Ocean liking scale scores that range from -100 (strongly dislike) to 100 (strongly like). 0 represents neutral.\n\\\n\\\n***Hypotheses:*** $H_0: \\mu = 0; H_a: \\mu \\neq 0$ \n\n### <span style=\"color: red;\">Question: How would you answer this question if you had unlimited resources (e.g., time, money, and patience)?</span>\n\n-----\n\n**Administer the Ocean liking scale to all 10,000 inhabitants in the population and calculate the population mean score. Is it 0?  If not, the inhabitants are not neutral on average.**\n\n\n-----\n\n## Ocean Liking Scale Scores in Full Population\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\npath_data <- \"data_lecture\"  # <1> \n\ndata <- read_csv(here::here(path_data, \"2_sampling_distributions_like_clean.csv\"), # <2>\n                 show_col_types = FALSE) \n```\n:::\n\n\n\n1. This path points to where your data is and should be a relative path from your R project. \n2. we use the `here()` function in the `here` package (`here::here()`) to define paths within a function. This approach (vs. `file.path()`) works well when using R Projects. \n\n-----\n\n***See also:***    \n`view()` allows you to open up the data frame in rstudio.    \n\n`glimpse()` is a useful function that you can pipe tibbles into when first reading them in. It shows you useful information, like number of rows and column, variable (column) names, a sample of what the data look like, and the class of each variable (e.g., double, character, factor).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 2\n$ subid      <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …\n$ like_score <dbl> -23.608554, -9.011961, 30.536791, 5.886441, -9.164940, 23.6…\n```\n\n\n:::\n:::\n\n\n\n\n\n-----\n\n`skim()` and other functions in the `skimr` package are helpful for quick summaries of your data (e.g., missingness, distribution, type of data)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  skimr::skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |data  |\n|Number of rows           |10000 |\n|Number of columns        |2     |\n|_______________________  |      |\n|Column type frequency:   |      |\n|numeric                  |2     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|      sd|     p0|     p25|    p50|     p75|     p100|hist  |\n|:-------------|---------:|-------------:|------:|-------:|------:|-------:|------:|-------:|--------:|:-----|\n|subid         |         0|             1| 5000.5| 2886.90|   1.00| 2500.75| 5000.5| 7500.25| 10000.00|▇▇▇▇▇ |\n|like_score    |         0|             1|    0.0|   23.67| -86.64|  -16.08|    0.1|   16.14|    84.46|▁▃▇▃▁ |\n\n\n:::\n:::\n\n\n\n\n-----\n\nIf we want less information about the distribution we can use `summarise` and specify the descriptive statistics we want.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  summarise(n = n(),\n            mean = mean(like_score),\n            sd = sd(like_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n      mean    sd\n  <int>     <dbl> <dbl>\n1 10000 -6.27e-16  23.7\n```\n\n\n:::\n:::\n\n\n\n\n\n-----\n\nYou can also pull out a few rows to look at your data. This can be done using `slice_head()` to pull out $n$ top rows of the data set, `slice_tail()` to pull out $n$ bottom rows of the data set, or `slice_sample()` to pull out a random $n$ of rows from the data set.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  slice_head(n = 5) \n\ndata |> \n  slice_tail(n = 5) \n\nset.seed(101) # <1>\ndata |> \n  slice_sample(n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  subid like_score\n  <dbl>      <dbl>\n1     1     -23.6 \n2     2      -9.01\n3     3      30.5 \n4     4       5.89\n5     5      -9.16\n# A tibble: 5 × 2\n  subid like_score\n  <dbl>      <dbl>\n1  9996     -16.6 \n2  9997      -8.37\n3  9998      18.6 \n4  9999     -16.2 \n5 10000     -17.0 \n# A tibble: 5 × 2\n  subid like_score\n  <dbl>      <dbl>\n1  8009     -27.0 \n2  2873     -41.5 \n3  3281      17.8 \n4  5562      27.4 \n5  5471      -9.84\n```\n\n\n:::\n:::\n\n\n\n\n1. Whenever you are using random numbers it is important to set a seed first (`set.seed()`). This ensures you can reproduce that randomness!\n\n-----\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_raw <- data |> \n  ggplot(aes(x = like_score)) +\n  geom_histogram(color = \"black\", fill = \"light grey\", bins = 20) + \n  scale_x_continuous(limits = c(-100, 100)) +\n  theme_classic() #<1>\n```\n:::\n\n\n\n1. We can use themes to customize the output of our figures. This can be piped into your `ggplot()` code or set globally at the top of your script using the code below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_set(theme_classic()) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_raw\n```\n\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n\n-----\n\n\n## Parameter Estimation and Testing\n\n### <span style=\"color: red;\">Question: What do you conclude?</span>\n\n-----\n\n**Inhabitants of the island are neutral on average on the Ocean Liking Scale; $\\mu$ = 0.**\n\n\n-----\n\n\n\n\n### <span style=\"color: red;\">Question: How confident are you about this conclusion?</span>\n\n-----\n\n**Excluding issues of measurement of the scale (i.e., reliability), you are 100% confident that the population mean score on this scale is 0 ($\\mu$ = 0).**\n\n\n-----\n\n### <span style=\"color: red;\">Question: Of course, this approach to answering a research question is not typical. Why? And how would you normally answer this question?</span>\n\n-----\n\n**You will very rarely have access to all scores in the population. Instead, you have to use inferential statistics to “infer” (estimate) the size of the population parameter from a sample.**\n\n\n-----\n\n## Obtain a Sample\n\nYou are a poor graduate student. All you can afford is $N = 10$. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2005) \ndata_sample_1 <- data |> \n   slice_sample(n = 10)\n\ndata_sample_1 |> \n  summarise(n = n(),\n            mean = mean(like_score),\n            sd = sd(like_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n  mean    sd\n  <int> <dbl> <dbl>\n1    10  2.14  19.4\n```\n\n\n:::\n:::\n\n\n\n\n### <span style=\"color: red;\">Question: What do you conclude and why?</span>\n\n-----\n\n**A sample mean of 2.14 is not 0. However, you know that the sample mean will not match the population mean exactly. How likely is it to get a sample mean of 2.14 if the population mean is 0 (think about it!)?**\n\n-----\n\nYour friend is a poor graduate student too. All she can afford is $N = 10$ too.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_sample_2 <- data |> \n   slice_sample(n = 10)\n\ndata_sample_2 |> \n  summarise(n = n(),\n            mean = mean(like_score),\n            sd = sd(like_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n  mean    sd\n  <int> <dbl> <dbl>\n1    10  1.74  23.0\n```\n\n\n:::\n:::\n\n\n\n\n### <span style=\"color: red;\">Question: What does she conclude and why?</span>\n\n-----\n\n**A sample mean of 1.74 is not 0. However, she knows that the sample mean will not match the population mean exactly. It is more likely to get a sample mean of 1.74 than 2.14 if the population mean is 0 but she still doesn’t know how likely either outcome is. What if she obtained a sample with mean of 30?**\n\n-----\n\n## Sampling Distribution of the Mean\n\nYou can construct a sampling distribution for any parameter estimate (e.g., mean, $s$, min, max, $r$, $b_0$, $b_1$).\n\\\n\\\nFor the mean, you can think of the sampling distribution conceptually as follows:  \n\n1. Imagine drawing many samples (lets say 1000 samples but in theory, the sampling distribution is infinite) of $N$=10 participants (10 participants in each sample) from your population.\n2. Next, calculate the mean for each of these samples of 10 participants.\n3. Finally, create a histogram (or density plot) of these sample means.\n\n-----\n\n### 1000 Samples of $N$=10\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_sample_mean <- function(data, n_sub) { # <1>\n  data |> \n  slice_sample(n = n_sub) |> \n  summarise(across(everything(), list(mean = mean, sd = sd), .names = \"{fn}\")) |> \n  mutate(n = n_sub) \n}\n```\n:::\n\n\n\n\n1. Here we are writing a function that we will use to generate descriptive statistics over 1000 samples. We are keeping this function generic because we are going to use this function again later in the chapter for more simulation examples!\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(101)\nsamples <- 1:1000 |> \n  map(\\(i) get_sample_mean(data = data[, \"like_score\"], n_sub = 10)) |>  #<1>\n  list_rbind()\n\nsamples\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 3\n     mean    sd     n\n    <dbl> <dbl> <dbl>\n 1 -6.89   22.4    10\n 2 11.9    20.2    10\n 3  0.147  15.9    10\n 4 -8.93   27.3    10\n 5  8.52   20.0    10\n 6  2.02   10.6    10\n 7 -0.198  16.9    10\n 8 -0.230  21.1    10\n 9  1.01   22.7    10\n10  6.26   28.4    10\n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n\n\n1. We use the `map()` function to repeat our function 1000 times. \n\n-----\n\n### Sampling Distribution of the Mean\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamples |> \n  summarise(n = n(), \n            mean_m = mean(mean), \n            sd = sd(mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n mean_m    sd\n  <int>  <dbl> <dbl>\n1  1000 -0.238  7.69\n```\n\n\n:::\n\n```{.r .cell-code}\nplot_samples <- samples |> \n  ggplot(aes(x = mean)) +\n  geom_histogram(color = \"black\", fill = \"light grey\", bins = 20) + \n  scale_x_continuous(\"sample means\", limits = c(-100, 100))\n\nplot_samples\n```\n\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n*Note: In your research, you don't form a sampling distribution by repeated sampling. You (typically) only have one sample.*\n\n-----\n\n## Raw Score Distribution vs. Sampling Distribution\n\nThe distinction between the raw score distribution and your sample distribution is very important to keep clear in your mind!\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork) # <1> \n```\n:::\n\n\n\n\n1. The `patchwork` package is an easy and customizable way to combine `ggplot()` objects. For more information see <https://patchwork.data-imaginist.com/>.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_raw + plot_samples\n```\n\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\n## Sampling Distribution of the Mean\n\n### <span style=\"color: red;\">Question: What will the mean of the sample means be?  In other words, what is the mean of the sampling distribution?</span>\n\n-----\n\n**The mean of the sample means (i.e., the mean of the sampling distribution) will equal the population mean of raw scores on the dependent measure.  This is important because it indicates that the sample mean is an unbiased estimator of the population mean.**\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\n***The mean is an unbiased estimator:*** The mean of the sample means will equal the mean of the population. Therefore, individual sample means will neither systematically under or overestimate the population mean.\n\\\n\\\n***Raw Ocean Liking Scores:***\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n mean_m    sd\n  <int>  <dbl> <dbl>\n1 10000      0  23.7\n```\n\n\n:::\n:::\n\n\n\n\\\n***Sample (N=10) Means:***\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n mean_m    sd\n  <int>  <dbl> <dbl>\n1  1000  -0.24  7.69\n```\n\n\n:::\n:::\n\n\n\n\nThe sample variance ($s^2$; with n-1 denominator) is also an unbiased estimator of the population variance ($\\sigma^2$). In other words, the mean of the sample $s^2$’s will approximate the population variance. Sample $s$ is negatively biased.\n\n-----\n\n### <span style=\"color: red;\">Question: Will all of the sample means be the same?</span>\n\n-----\n\n**No, there was a distribution of means that varied from each other. The mean of the sampling distribution was the population mean but the standard deviation was not zero.**\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n mean_m    sd\n  <int>  <dbl> <dbl>\n1  1000  -0.24  7.69\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\n## Standard Error(SE)\n\nThe standard deviation of the sampling distribution (i.e., standard deviation of the infinite sample means) is equal to:   \n\\\n$\\frac{\\sigma}{\\sqrt{N_{sample}}}$\n\\\n\\\nWhere $\\sigma$ is the standard deviation of the population raw scores.  \n\\\n\\\nThis variability in the sampling distribution is due to sampling error.  \n\\\n\\\nTherefore, because we use parameter estimates calculated in our sample to estimate population parameters, we would like to minimize sampling error.\n\\\n\\\nThe standard deviation of the sampling distribution for a parameter estimate has a technical name.  It is called the standard error of the parameter estimate.  Here, we are talking about the standard error of the mean.\n\n-----\n\n### <span style=\"color: red;\">Question: What factors affect the size of the sampling error of the mean (i.e., the standard error)?</span>\n\n-----\n\n**The standard deviation of the population raw scores and the sample size.**\n\n-----\n\n### <span style=\"color: red;\">Question: Variation among raw scores for a variable in the population is broadly caused by two factors. What  are they?</span>\n\n-----\n\n**1.  Individual differences**   \n**2.  Measurement error (the opposite of reliability)**\n\n-----\n\n### <span style=\"color: red;\">Question: What is the relationship between population variability ($\\sigma$) and SE?</span>\n\n-----\n\n**As the variability of the variable increases in the population, the SE increases.**   \n\n\n-----\n\n### <span style=\"color: red;\">Question: What would happen to SE if there was no variation in population scores?</span>\n\n-----\n\n**The SE would equal 0 no matter which participants you sampled. They would all have the same scores!**   \n\n\n-----\n\n### <span style=\"color: red;\">Question: What is the relationship between sample size and SE?</span>\n\n-----\n\n**As the sample size increases, the SE for the statistic will decrease.**   \n\n-----\n\n### <span style=\"color: red;\">Question: What would the SE be if the sample size equalled population size?</span>\n\n-----\n\n**If the sample contained all participants from the population, the SE would be equal to 0 because each sample mean would have exactly the same value as the overall population mean (because all same scores).**   \n\n-----\n\n### <span style=\"color: red;\">Question: What would happen if the samples contained only 1 participant?</span>\n\n-----\n\n**If each sample contained only 1 participant, the SE would be equal to the variation ($\\sigma$) observed within the population.**   \n\n-----\n\n## Shape of the Sampling Distribution\n\n***Central Limit Theorem:*** The shape of the sampling distribution approaches normal as $N$ increases. \n\\\n\\\nThe shape is roughly normal even for moderate sample sizes assuming that the original distribution isn’t really weird (i.e., non-normal). \n\n-----\n\n## Normal Population and Various Sampling Distributions\n\nPopulation size: 100,000; Simulated 10,000 samples.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n\n-----\n\n## Uniform Population and Various Sampling Distributions\n\nPopulation size: 100,000; Simulated 10,000 samples.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n-----\n\n## Skewed Population and Various Sampling Distributions\n\nPopulation size: 100,000; Simulated 10,000 samples.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\n## An Important Normal Distribution: Z-scores\n\nThe $z$ distribution contains normally distributed scores with a mean of 0 and a standard deviation of 1.\n\\\n\\\nYou can therefore think of any specific z-score as telling you the position of the score in terms of standard deviations above the mean.\n\\\n\\\nThe probability distribution is known for the $z$ distribution.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-31-1.png){width=768}\n:::\n:::\n\n\n\n\n\n-----\n\n## Probability of Parameter Estimate Given $H_0$\n\nHow could you use the $z$ distribution to determine the probability of obtaining a sample mean (parameter estimate) of 2.40 if you draw a sample of $N=10$ from a population of Ocean Liking scores with a population mean (parameter) of 0?\n\\\n\\\nThink about it……\n\n-----\n\n## Hypothetical Sampling Distribution for $H_0$\n\nIf $H_0$ is true; the sampling distribution has a mean of 0 and standard deviation of $\\frac{\\sigma}{\\sqrt{N_{sample}}} =  \\frac{23.7}{\\sqrt{10}}  =  7.5$.   \n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\n\n### <span style=\"color: red;\">Question: If $H_0$ is true and this is the sampling distribution (in blue), how likely is it to get a sample mean of 2.4 or more extreme?</span>\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\n**Pretty likely…**   \n**But we can do better than that!**\n\n-----\n\n## Our First Inferential Test: The z-test\n\n$z = \\frac{2.4 - 0}{7.5} = 0.32; p \\le .749$  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(0.32, mean=0, sd=1, lower.tail=FALSE) * 2 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7489683\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\n\n\n-----\n\n## $t$ vs. $z$\n\n$z = \\frac{2.4 - 0}{7.5} = 0.32$  \n\n### <span style=\"color: red;\">Question: Where did we get the 2.4 from in our z-test?</span>\n\n-----\n\n**Our sample mean from our study. This is our parameter estimate of the population mean of OLS (like_score) scores.**   \n\n-----\n\n### <span style=\"color: red;\">Question: Where did we get the 7.5 from in our z-test and what is the problem with this?</span>\n\n-----\n\n**This was our estimate of the standard deviation of the sampling distribution.**  \n\\\n\\\n**$\\frac{\\sigma}{\\sqrt{N_{sample}}}$**  \n\\\n\\\n**We do not know $\\sigma$.**   \n\n-----\n\n### <span style=\"color: red;\">Question: How can we estimate $\\sigma$?</span>\n\n-----\n\n**We can use our sample standard deviation ($s$), but $s$ is a negatively biased parameter estimate.  On average, it will underestimate $\\sigma$.**   \n\n-----\n\n### <span style=\"color: red;\">Question: So what do we do?</span>\n\n-----\n\n**\"We account for this underestimation of $\\sigma$ and therefore of the standard deviation (standard error) of the sampling distribution by using the t distribution rather than the $z$ distribution to calculate the probability of our parameter estimate if $H_0$ is true.**    \n\\\n\\\n**The t distribution is slightly wider, particularly for small sample sizes to correct for our underestimate of the standard deviation.**\n\n-----\n\n## Our Second Inferential Test: One Sample t-test\n\n$t(df)$ = $\\frac{\\text{Parameter estimate – Parameter:} H_0}{\\text{Standard error of parameter estimate}}$   \n\\          \nWhere $SE$ is estimated using $s$ from sample data.\n\\\n$df = N – P = 10 - 1 = 9$\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\n\n-----\n\nThe bias in $s$ decreases with increasing $N$.  Therefore, $t$ approaches $z$ with larger sample sizes.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_sampling_distributions_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n\n\n\n-----\n\n## Null Hypothesis Significance Testing (NHST)\n\n1. Divide reality regarding the size of the population parameter into two non-overlapping possibilities: Null hypothesis ($H_0$) & Alternate hypothesis ($H_a$).    \n\n2. Assume that $H_0$ is true.\n\n3. Collect data.\n\n4. Calculate the probability ($p$-value) of  obtaining your parameter estimate (or a more extreme estimate) given your assumption (i.e., $H_0$ is true)\n\n5. Compare probability to some cut-off value (alpha level).\n\n6. (a) If this parameter estimate is less probable than cut-off value, reject $H_0$ in favor of $H_a$.\n\n   (b) If data is not less probable, fail to reject $H_0$.\n",
    "supporting": [
      "02_sampling_distributions_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}