{
  "hash": "2977d9bb79b342d480d2be4be68d29c1",
  "result": {
    "engine": "knitr",
    "markdown": "---\noutput: html_document\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n# Suppression {.unnumbered}\n\nIn the following examples, we will explore suppression using path diagrams and regression models.   \n\n- We use two related examples to illustrate when suppression will not vs. will occur.\n- In both examples, we have two predictors (X1 and X2) that positively predict an outcome (Y).\n- In the first example, the predictors are positively correlated.  In the second example, the predictors are negatively correlated.\n- We have folded some of the code to avoid having it distract from the main points.  However, you may want to look at the code to see how the data were generated and also how we use `ggdiagram` to create the path diagrams.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n-------------------------------------------------------------------------------\n\n## Example 1: No suppression\n\nGenerate positively correlated predictors with positive effect on y \n\n- Study hours (x1)\n- IQ (x2)\n- predict academic performance (y)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(123)\nmu <- c(0, 0, 10)\nsigma <- matrix(c(1, 0.4, 0.6,\n                  0.4, 1, 0.3,\n                  0.6, 0.3, 1), nrow = 3)\n\nd_pos <- MASS::mvrnorm(n = 100, mu = mu, Sigma = sigma,\n                       empirical = TRUE)\ncolnames(d_pos) <- c(\"x1\", \"x2\", \"y\")\nd_pos <- as_tibble(d_pos)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(d_pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    x1  x2   y\nx1 1.0 0.4 0.6\nx2 0.4 1.0 0.3\ny  0.6 0.3 1.0\n```\n\n\n:::\n:::\n\n\n\n\n-------------------------------------------------------------------------------\n\nOverall effect of x1 on y\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_yx1 <- lm(y ~ x1, data = d_pos)\nm_yx1 |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)   10        0.0804    124.   1.15e-109\n2 x1             0.600    0.0808      7.42 4.19e- 11\n```\n\n\n:::\n:::\n\n\n\n\nOverall effect of x2 on y\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_yx2 <- lm(y ~ x2, data = d_pos) \nm_yx2 |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)     10      0.0959    104.   3.13e-102\n2 x2               0.3    0.0964      3.11 2.43e-  3\n```\n\n\n:::\n:::\n\n\n\n\nPartial (direct, unique) effects of x1 and x2 on y.  NOTICE: Partial effects are SMALLER than OVERALL effects.  This is typical.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_yx12 <- lm(y ~ x1 + x2, data = d_pos)\nm_yx12 |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)  10         0.0805   124.    1.05e-108\n2 x1            0.571     0.0883     6.47  4.01e-  9\n3 x2            0.0714    0.0883     0.809 4.21e-  1\n```\n\n\n:::\n:::\n\n\n\n\n-------------------------------------------------------------------------------\n\n## Path diagrams: X1 focus\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nx1 <- ob_rectangle(width = 3, height = 1, label = \"X1\", color = \"black\",\n                   x = 0, y = 3, fill = \"lightblue\")\nx2 <- ob_rectangle(width = 3, height = 1, label = \"X2\", color = \"black\",\n                   x = 0, y = -3, fill = \"lightblue\")\ny1 <- ob_rectangle(width = 3, height = 1, label = \"Y\", color = \"black\",\n                   x = 6, y = 3, fill = \"lightgreen\")\ny2 <- ob_rectangle(width = 3, height = 1, label = \"Y\", color = \"black\",\n                   x = 6, y = -3, fill = \"lightgreen\")\ny12 <- ob_rectangle(width = 3, height = 1, label = \"Y\", color = \"black\",\n                    x = 6, y = 0, fill = \"lightgreen\") \n  \npd_x1 <- ggdiagram() +\n  x1 +\n  y1 +\n  connect(x1, y1, label = 0.6, resect = 2)\n\npd_x2 <- ggdiagram() +\n  x2 +\n  y2 +\n  connect(x2, y2, label = 0.3, resect = 2)\n\npd_x12 <- ggdiagram() +\n  x1 +\n  x2 +\n  y12 +\n  connect(x1, y12, label = 0.571, resect = 2) +\n  connect(x2, y12, label = 0.071, resect = 2) +\n  ob_covariance(x1, x2, label = 0.4)\n\ncowplot::plot_grid(pd_x1, pd_x12, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](app3_suppression_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\nX1 effects on Y\n\n- Total effect: 0.6\n- Direct effect of X1 on Y controlling for X2: 0.571\n- Spurious/Indirect effect of X1 on Y through X2: 0.029 (0.4 * 0.071)\n- 0.6 = 0.571 + 0.029\n\nDirect effect of X1 < total effect of X1 (because spurious/indirect effect is non-zero and in same direction as direct effect)\n\n-------------------------------------------------------------------------------\n\n## Path diagrams: X2 focus\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](app3_suppression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nX2 effects on Y\n\n- Total effect of X2: 0.3\n- Direct effect of X2 on Y controlling for X1: 0.071\n- Spurious/Indirect effect of X1 on Y through X2: 0.229 (0.4 * 0.571)\n- 0.3 = 0.071+ 0.229\n\nDirect effect of X2 < total effect of X2 (because spurious/indirect effect is non-zero and in same direction as direct effect)\n\n-------------------------------------------------------------------------------\n\n## Example 2: Suppression\n\nNegatively correlated predictors with positive effects on y\n\n- Study hours (x1)\n- Social confidence (x2)\n- predict academic performance (y)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nmu <- c(0, 0, 10)\nsigma <- matrix(c(1, -0.4, 0.6,\n                  -0.4, 1, 0.3,\n                  0.6, 0.3, 1), nrow = 3)\n\nd_mixed <- MASS::mvrnorm(n = 100, mu = mu, Sigma = sigma,\n                    empirical = TRUE)\ncolnames(d_mixed) <- c(\"x1\", \"x2\", \"y\")\nd_mixed <- as_tibble(d_mixed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(d_mixed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     x1   x2   y\nx1  1.0 -0.4 0.6\nx2 -0.4  1.0 0.3\ny   0.6  0.3 1.0\n```\n\n\n:::\n:::\n\n\n\n\n-------------------------------------------------------------------------------\n\nOverall effect of x1 on y\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_yx1 <- lm(y ~ x1, data = d_mixed)\nm2_yx1 |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)   10        0.0804    124.   1.15e-109\n2 x1             0.600    0.0808      7.42 4.19e- 11\n```\n\n\n:::\n:::\n\n\n\n\nOverall effect of x2 on y\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_yx2 <- lm(y ~ x2, data = d_mixed) \nm2_yx2 |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)     10      0.0959    104.   3.13e-102\n2 x2               0.3    0.0964      3.11 2.43e-  3\n```\n\n\n:::\n:::\n\n\n\n\nPartial (direct, unique) effects of x1 and x2 on y.  NOTICE: Partial effects are BIGGER than OVERALL effects.  This is referred to as suppression.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_yx12 <- lm(y ~ x1 + x2, data = d_mixed)\nm2_yx12 |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)   10        0.0547     183.  5.86e-125\n2 x1             0.857    0.0600      14.3 1.29e- 25\n3 x2             0.643    0.0600      10.7 3.71e- 18\n```\n\n\n:::\n:::\n\n\n\n\n-------------------------------------------------------------------------------\n\n## Path diagrams: X1 focus\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](app3_suppression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\nX1 effects on Y\n\n- Total effect of X1: 0.6\n- Direct effect of X1 on Y controlling for X2: 0.857\n- Spurious/Indirect effect of X1 on Y through X2: -0.257 (-0.4 * 0.643)\n- 0.6 = 0.857 + -0.257\n\nDirect effect of X1 > total effect of X1 (because spurious/indirect effect is non-zero and in opposite direction as direct effect)\n\n-------------------------------------------------------------------------------\n\n## Path diagrams: X2 focus\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](app3_suppression_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\nX2 effects on Y\n\n- Total effect of X2 on Y: 0.3\n- Direct effect of X2 on Y controlling for X1: 0.643\n- Spurious/Indirect effect of X1 on Y through X2: -0.343 (-0.4 * 0.857)\n- 0.3 = 0.643 + -0.343\n\nDirect effect of X2 > total effect of X2 (because spurious/indirect effect is non-zero and in opposite direction as direct effect)\n\n-------------------------------------------------------------------------------\n\n## Suppression\n\nSuppression exists when partial (direct, unique) predictor effects are (1) larger in magnitude or (2) opposite in sign relative to their overall effects\n\n\\\n\nThis occurs when the direct and indirect effects of a predictor on the outcome work in opposite directions.\n",
    "supporting": [
      "app3_suppression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}