{
  "hash": "6eabb826ef195079659042b35926b7c0",
  "result": {
    "engine": "knitr",
    "markdown": "--- \noutput: html_document \neditor_options:  \n  chunk_output_type: console\n--- \n\n \n\n# Inferences about Two Continuous Predictors and their Interaction\n\n\n::: {.cell}\n\n:::\n\n\n\n## Interactive Models: Two Quantitative Variables\n\n**Example:**   \n\nEffect of positive attitudes (1-5) about birth control and peer pressure to not use birth control (1-5) on intention to use birth control (0-30) among sexually active female adolescents.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(conflicts.policy = \"depends.ok\") \nlibrary(tidyverse)\nlibrary(patchwork)\n\ntheme_set(theme_classic()) \n\npath_data <- \"data_lecture\"\n\ndata <- read_csv(here::here(path_data, \"10_interactions_birth_control.csv\"),\n                 show_col_types = FALSE) |> \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 125\nColumns: 4\n$ subid <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…\n$ att   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ pp    <dbl> 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5…\n$ bc    <dbl> 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4…\n```\n\n\n:::\n:::\n\n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  pivot_longer(att:bc, names_to = \"var\") |> \n  group_by(var) |> \n  summarise(mean = mean(value), \n            sd = sd(value), \n            min = min(value), \n            max = max(value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  var    mean    sd   min   max\n  <chr> <dbl> <dbl> <dbl> <dbl>\n1 att       3  1.42     1     5\n2 bc       11  5.68     3    27\n3 pp        3  1.42     1     5\n```\n\n\n:::\n:::\n\n\n\n-----\n\n<span style=\"color: red;\">Question: If you regressed BC on Att and PP in two separate linear models, what can you tell me about these two models based on the correlations below?</span>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  select(-subid) |> \n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     att   pp    bc\natt 1.00  0.0  0.75\npp  0.00  1.0 -0.50\nbc  0.75 -0.5  1.00\n```\n\n\n:::\n:::\n\n\n\n-----\n\n<span style=\"color: blue;\">Regression coefficient for Att will be positive. Regression coefficient for PP will be negative. $R^2$ will be bigger for Att model ($R^2$ = .56) than for PP model ($R^2$ = .25)</span>\n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_att <- lm (bc ~ att, data = data)\n\nbroom::tidy(m_att)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     2.00     0.791      2.53 1.27e- 2\n2 att             3.00     0.239     12.6  7.92e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_att)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5625\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nm_pp <- lm (bc ~ pp, data = data)\n\nbroom::tidy(m_pp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     17.0     1.04      16.4  9.08e-33\n2 pp              -2       0.312     -6.40 2.91e- 9\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_pp)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.25\n```\n\n\n:::\n:::\n\n\n\n-----\n\n<span style=\"color: red;\">Question: Based on the correlations, what can you tell me about the model including both Att and PP as regressors?</span>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  select(-subid) |> \n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     att   pp    bc\natt 1.00  0.0  0.75\npp  0.00  1.0 -0.50\nbc  0.75 -0.5  1.00\n```\n\n\n:::\n:::\n\n\n-----\n\n<span style=\"color: blue;\">The regression coefficients for Att and PP will match the coefficients from their respective bivariate models b/c Att and PP are fully orthogonal (uncorrelated). PP and Att each predict fully unique variance in BC.</span>   \n\n<span style=\"color: blue;\">The $R^2$ for the additive model will be equal to the sum of the $R^2$s from the two bivariate models, again b/c Att and PP are orthogonal.</span>\n\n-----\n\n<span style=\"color: red;\">Question: What about $\\eta_p^2$ for Att (or PP) in the 1 predictor model vs. the 2 predictor model? Specify the augmented and compact models to test Att for 1 and 2 predictor approaches. Specify the formula for $\\eta_p^2$.</span>\n\n-----\n\n<span style=\"color: blue;\">**Test for Att in 1 predictor model:**</span>   \n\n<span style=\"color: blue;\">$\\text{BC}_a = b_0 + b_1*\\text{Att}$</span>    \n<span style=\"color: blue;\">$\\text{BC}_c = b_0 + 0*\\text{Att}$</span>    \n\n\n<span style=\"color: blue;\">**Test for Att in 2 predictor model:**</span>   \n\n<span style=\"color: blue;\">$\\text{BC}_a = b_0 + b_1*\\text{Att} + b_2*\\text{PP}$</span>  \n<span style=\"color: blue;\">$\\text{BC}_c = b_0 + 0*\\text{Att}+ b_2*\\text{PP}$</span>   \n\n\n<span style=\"color: blue;\">$\\eta_p^2 = \\frac{\\text{SSE}_c - \\text{SSE}_a}{\\text{SSE}_c}$</span>   \n\n- <span style=\"color: blue;\">Numerator is same for the both 1 and 2 predictor tests of Att.</span>   \n- <span style=\"color: blue;\">Denominator is smaller for 2 predictor test.</span>   \n- <span style=\"color: blue;\">Therefore, $\\eta_p^2$ for Att is bigger in 2 predictor model. Att produces a bigger proportional reduction in error.</span>\n\n-----\n\n\n<span style=\"color: red;\">Question: What about $\\Delta R^2$ for Att (or PP) in the 1 predictor model vs. the 2 predictor model? Specify the augmented and compact models to test Att for 1 and 2 predictor approaches. Specify the formula for $\\Delta R^2$.</span>\n\n-----\n\n<span style=\"color: blue;\">**Test for Att in 1 predictor model:**</span>   \n\n<span style=\"color: blue;\">$\\text{BC}_a = b_0 + b_1*\\text{Att}$</span>    \n<span style=\"color: blue;\">$\\text{BC}_c = b_0 + 0*\\text{Att}$</span>    \n\n\n<span style=\"color: blue;\">**Test for Att in 2 predictor model:**</span>   \n\n<span style=\"color: blue;\">$\\text{BC}_a = b_0 + b_1*\\text{Att} + b_2*\\text{PP}$</span>  \n<span style=\"color: blue;\">$\\text{BC}_c = b_0 + 0*\\text{Att}+ b_2*\\text{PP}$</span>   \n\n\n<span style=\"color: blue;\">$\\Delta R^2 = \\frac{\\text{SSE}_c - \\text{SSE}_a}{\\text{SSE}_\\text{mean only}}$</span>   \n\n- <span style=\"color: blue;\">Numerator is same for the both 1 and 2 predictor tests of Att.</span>   \n- <span style=\"color: blue;\">Denominator is same for both 1 and 2 predictor tests.</span>   \n- <span style=\"color: blue;\">Therefore, $\\Delta R^2$ for Att does not change. Att explains the same proportion of **total** variance (error) in both models.</span>\n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_add <- lm(bc ~ att + pp, data = data)\n\nbroom::tidy(m_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     8.00     0.701      11.4 5.84e-21\n2 att             3.00     0.157      19.1 1.56e-38\n3 pp             -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n:::\n\n\n$\\text{BC} = 8.0 + 3.0 * \\text{Att} + -2.0*\\text{PP}$   \n\n\n<span style=\"color: red;\">Question: What has this model required (or what havent we tested for)?</span>\n\n-----\n\n<span style=\"color: blue;\">It requires that the effect of each IV on the DV is constant across all levels/scores of the other IV.</span>   \n\n<span style=\"color: blue;\">We have not tested for an interaction.</span>\n\n-----\n\n<span style=\"color: red;\">Question: Where are $b_\\text{Att}, b_\\text{PP},$ and $b_0$ in the figure below?</span>\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npreds <- expand.grid(att = 1:5, pp = c(1, 3, 5))\npreds_y <- predict(m_add, newdata = preds)\n\nplot_m_add <- ggplot() +\n  geom_line(aes(x = preds$att, y = preds_y, color = factor(preds$pp)), \n            linewidth = 1) +\n  labs(x = \"Attitude about Birth Control\",\n       y = \"Birth Control Use\",\n       color = \"Peer Pressure\") \n\nplot_m_add\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n-----\n\n<span style=\"color: blue;\">$b_\\text{Att}$ = slope of lines. Constant for all three lines.</span>    \n\n<span style=\"color: blue;\">$b_\\text{PP}$ = separation of lines. Lines are separated by $2*b_\\text{PP}$. Constant across Att.</span>    \n\n<span style=\"color: blue;\">$b_0$ = predicted value at Att = 0 and PP= 0. Not displayed in figure.</span> \n\n-----\n\n<span style=\"color: red;\">Question: How might we benefit from including a third regressor in the model to represent the interaction between Att and PP? Hint, there are two benefits.</span>\n\n-----\n\n1. <span style=\"color: blue;\">If Att X PP effect is significant, it will increase $R^2$, decrease SEs, and therefore increase power to test all effects.</span>   \n\n2. <span style=\"color: blue;\">If Att X PP is significant, it will provide us with a more complex, nuanced perspective on the nature of the Att and PP effects on BC.</span>  \n\n**Definition: An interaction exists when the effect of 1 predictor on the DV differs across levels/values of the other predictor.**  \n\n<!-- John, you also had this note on your slide \"LINK to additive results in this example…\" I wasn't sure what it meant-->\n\n-----\n\n- Regressors for interaction terms are calculated as the product of the regressors (for the predictors) in the interaction. In this case, we simply multiply Att X PP.   \n\n- You will typically want to **center** the IVs in the primary model to yield tests of *main effects* of each IV as well as tests of the interaction (More on this as the slides develop).     \n\n- In R, you don’t need to actually compute the product term regressor directly. `A:B` in the `lm()` formula will include the A X B interaction regressor(s).    \n\n- `A*B` is further shorthand to include A, B, and A X B in the model.   \n\n- You should **not** include A X B in a model that does not include lower order effects (e.g., A, and B).    \n\n-----\n\n<span style=\"color: red;\">Question: What will change in the two predictor model if we center both IVs?</span>\n\n-----\n\n1. <span style=\"color: blue;\">$b_0$ and its SE will change. $b_0$ is the predicted value at 0 on all regressors in the model.</span> <span style=\"color: red;\">Will SE be bigger or smaller in centered model?</span>    \n\n2. <span style=\"color: blue;\">$b_\\text{Att}$ and $b_\\text{PP}$ (and their SEs) will remain the same. The additive model forces the effect for each IV to be same across all values of other regressors. Therefore, the effect of ATT is the same if PP = 0 or PP= 1, or PP=3, etc. Given this, centering PP does not change $b$ for ATT.</span>    \n\n3. <span style=\"color: blue;\">Of course, $R^2$ also remains the same.</span>\n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(m_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     8.00     0.701      11.4 5.84e-21\n2 att             3.00     0.157      19.1 1.56e-38\n3 pp             -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_add)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(att_c = att - mean(att),\n         pp_c = pp - mean(pp))\n\nm_add_c <- lm(bc ~ att_c + pp_c, data = data)\n\nbroom::tidy(m_add_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    11        0.222      49.6 1.01e-82\n2 att_c           3.00     0.157      19.1 1.56e-38\n3 pp_c           -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_add_c)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n\n-----\n\n<span style=\"color: red;\">Question: What will change when we add the interaction term (with centered IVs) relative to the centered two predictor model?</span>\n\n-----\n\n1. <span style=\"color: blue;\">An additional regressor will be included for Att x PP.</span>  \n\n2. <span style=\"color: blue;\">If Att x PP accounts for DV variance, $R^2$ will increase and SEs for coefficients (and intercept) will be reduced.</span>  \n\n3. <span style=\"color: blue;\">$b_0$ will remain the predicted value at 0 for all regressors. No change from centered two predictor model.</span>  \n\n4. <span style=\"color: blue;\">$b_\\text{Att}$ and $b_\\text{PP}$ are respective effects at 0 on all other regressors. Including an interaction now allows for each IV effect to vary across levels/values of other IVs.</span>    \n\n    <span style=\"color: blue;\">Thus, $b_\\text{Att}$ is now the (*simple*) effect of Att at PP (centered) = 0 and the $b_\\text{PP}$ is now the (*simple*) effect of PP at Att (centered) = 0.</span>  \n\n-----\n\n## Main Effects and Simple Effects\n\nIn ANOVA terms, The **Main Effect** of an IV is the overall effect of that IV on the DV averaging across the levels of the other IV(s) in the model.      \n\nA **Simple Effect** of an IV is the effect of that IV at a specific level of the other IV(s) in the model.     \n\nFrom this perspective, you can think about a main effect as a special simple effect where the specific level of the other IV is its average value.    \n\n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_c <- lm(bc ~ att_c * pp_c, data = data)\n\nbroom::tidy(m_int_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    11       0.129       85.6 4.33e-110\n2 att_c           3.00    0.0909      33.0 2.41e- 62\n3 pp_c           -2.00    0.0909     -22   4.16e- 44\n4 att_c:pp_c     -1       0.0643     -15.6 1.20e- 30\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_int_c)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9375\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(m_add_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    11        0.222      49.6 1.01e-82\n2 att_c           3.00     0.157      19.1 1.56e-38\n3 pp_c           -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_add_c)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n\n-----\n\n$\\text{BC} = 11.0 + 3.0 * \\text{Att}_c + -2.0*\\text{PP}_c$    \n\n$\\text{BC} = 11.0 + 3.0 * \\text{Att}_c + -2.0*\\text{PP}_c + -1.0*\\text{Att}_c*\\text{PP}_c$     \n\n\n<span style=\"color: red;\">Link intercepts and coefficients from each model to their respective figures.</span>    \n\n*Note:* figures use raw (not centered) predictors. Means for both predictors are 3.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nm_int <- lm(bc ~ att * pp, data = data)\n\npreds_int_y <- predict(m_int, newdata = preds)\n\nplot_m_int <- ggplot() +\n  geom_line(aes(x = preds$att, y = preds_int_y, color = factor(preds$pp)), \n            linewidth = 1) +\n  labs(x = \"Attitude about Birth Control\",\n       y = \"Birth Control Use\",\n       color = \"Peer Pressure\") \n\nplot_m_add + plot_m_int\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n-----\n\n$\\text{BC} = 11.0 + 3.0 * \\text{Att}_c + -2.0*\\text{PP}_c + -1.0*\\text{Att}_c*\\text{PP}_c$     \n\n<span style=\"color: red;\">Question: What would the interactive model look like if we hadn’t centered each IV?</span>   \n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int <- lm(bc ~ att * pp, data = data) \n\nbroom::tidy(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -1.00    0.707      -1.41 1.60e- 1\n2 att             6.00    0.213      28.1  6.17e-55\n3 pp              1       0.213       4.69 7.23e- 6\n4 att:pp         -1       0.0643    -15.6  1.20e-30\n```\n\n\n:::\n\n```{.r .cell-code}\nbroom::glance(m_int)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9375\n```\n\n\n:::\n:::\n\n\n-----\n\n$\\text{BC} = 11.0 + 3.0 * \\text{Att}_c + -2.0*\\text{PP}_c + -1.0*\\text{Att}_c*\\text{PP}_c$ \n\n$\\text{BC} = -1.0 + 6.0 * \\text{Att} + 1.0*\\text{PP} + -1.0*\\text{Att}*\\text{PP}$   \n\n<span style=\"color: red;\">Link intercept and coefficients from the raw model to the expanded figure below on right.</span>   \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npreds_expanded <- expand.grid(att = 0:5, pp = 0:5)\npreds_int_y_expanded <- predict(m_int, newdata = preds_expanded)\n\nplot_m_int_expanded <- ggplot() +\n  geom_line(aes(x = preds_expanded$att, y = preds_int_y_expanded, \n                color = factor(preds_expanded$pp)), \n            linewidth = 1) +\n  labs(x = \"Attitude about Birth Control\",\n       y = \"Birth Control Use\",\n       color = \"Peer Pressure\") \n\nplot_m_int + plot_m_int_expanded\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n-----\n\n$\\text{BC} = 11.0 + 3.0 * \\text{Att}_c + -2.0*\\text{PP}_c + -1.0*\\text{Att}_c*\\text{PP}_c$ \n\n$\\text{BC} = -1.0 + 6.0 * \\text{Att} + 1.0*\\text{PP} + -1.0*\\text{Att}*\\text{PP}$    \n\n\n<span style=\"color: red;\">Question: So what does $b_{\\text{Att}*\\text{PP}}$ indicate?</span>   \n\n-----\n\n<span style=\"color: blue;\">The coefficient for the interaction indicates how the simple effect of each IV changes for a one unit increase on the other IV.</span>    \n\n\n**The interaction coefficient applies symmetrically to both IV effects.**\n\n-----\n\nConsidering Att in raw model:   \n\n- Att effect is 6 for PP = 0    \n- Att effect is 5 for PP = 1    \n- Att effect is 4 for PP = 2    \n- Att effect is 3 for PP = 3   \n- Att effect is 2 for PP = 4   \n- Att effect is 1 for PP = 5    \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_m_int_expanded\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n-----\n\nConsidering PP in raw model:   \n\n- PP effect is 1 for Att = 0   \n- PP effect is 0 for Att = 1    \n- PP effect is -1 for Att = 2    \n- PP effect is -2 for Att = 3    \n- PP effect is -3 for Att = 4    \n- PP effect is -4 for Att = 5     \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_m_int_expanded\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n-----\n\n## Interactive Models: Coefficient Magnitudes\n\n- Interaction and its test is obtained from any model (regardless of centering).    \n\n- *Main* effects of IVs are obtained from model with all IVs centered on mean. You may or may not choose to report these main effects depending on the situation.     \n\n- Magnitude of *simple* effects of either IV can be calculated directly from the raw or centered model (I prefer the raw model for ease of thinking in raw units). <span style=\"color: red;\">How?</span>\n\n-----\n\n## Interactive Models: Raw Model Coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int <- lm(bc ~ att * pp, data = data) \nbroom::tidy(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -1.00    0.707      -1.41 1.60e- 1\n2 att             6.00    0.213      28.1  6.17e-55\n3 pp              1       0.213       4.69 7.23e- 6\n4 att:pp         -1       0.0643    -15.6  1.20e-30\n```\n\n\n:::\n:::\n\n\n-----\n\n## Interactive Models: Simple Effect Magnitudes\n\nMagnitude of *simple* effects of either IV can be calculated directly from the raw or centered model (I prefer the raw model for ease of thinking in raw units). <span style=\"color: red;\">How?</span>   \n\n$\\text{BC} = -1.0 + 6.0 * \\text{Att} + 1.0*\\text{PP} + -1.0*\\text{Att}*\\text{PP}$   \n\n<span style=\"color: blue;\">Effect of Att = 6.0 + -1.0 * PP</span>    \n<span style=\"color: blue;\">Effect of PP = 1.0 + -1.0 * Att</span>     \n\n<span style=\"color: red;\">Question: How could you obtain formal significance tests for any specific simple effects (e.g., effect of Att at PP = 1, 3, & 5)?</span>\n\n-----\n\n$\\text{BC} = -1.0 + 6.0 * \\text{Att} + 1.0*\\text{PP} + -1.0*\\text{Att}*\\text{PP}$   \n\n<span style=\"color: blue;\">Effect of Att = 6.0 + -1.0 * PP</span>    \n<span style=\"color: blue;\">Effect of Att = 6.0 + -1.0 * (1) = 5</span>    \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(pp_1 = pp - 1)\n\nm_pp_1 <- lm(bc ~ att * pp_1, data = data)\nbroom::tidy(m_pp_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) -2.54e-14    0.522  -4.87e-14 1.00e+ 0\n2 att          5.00e+ 0    0.157   3.18e+ 1 1.57e-60\n3 pp_1         1.00e+ 0    0.213   4.69e+ 0 7.23e- 6\n4 att:pp_1    -1.00e+ 0    0.0643 -1.56e+ 1 1.20e-30\n```\n\n\n:::\n:::\n\n\n\n-----\n\n\n$\\text{BC} = -1.0 + 6.0 * \\text{Att} + 1.0*\\text{PP} + -1.0*\\text{Att}*\\text{PP}$   \n\n<span style=\"color: blue;\">Effect of Att = 6.0 + -1.0 * PP</span>    \n<span style=\"color: blue;\">Effect of Att = 6.0 + -1.0 * (5) = 1</span>    \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(pp_5 = pp - 5)\n\nm_pp_5 <- lm(bc ~ att * pp_5, data = data)\nbroom::tidy(m_pp_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     4.00    0.522       7.66 5.12e-12\n2 att             1.00    0.157       6.35 3.91e- 9\n3 pp_5            1.00    0.213       4.69 7.23e- 6\n4 att:pp_5       -1       0.0643    -15.6  1.20e-30\n```\n\n\n:::\n:::\n\n\n-----\n\n## Interactive Models: Reporting Considerations\n\n<span style=\"color: red;\">Question: So what do you report and in what order?</span>\n\n-----\n\n<span style=\"color: blue;\">There is no one answer here.  Some say you never report main effects when there are significant interactions.  This camp would say, report only interaction and possibly simple effects.</span>    \n\n<span style=\"color: blue;\">Others (including me) believe that main effects are sometimes useful to report even when interaction is significant. *Main* effects (effect at “mean” of other IV) provides an anchor for effect. The interaction then indicates how this effect changes across values of the other IV. *Simple* effects can sometimes allow you to describe further how this effect changes at various values of other IV.</span>    \n\n<span style=\"color: blue;\">The other complexity surrounds the nature of the two IVs.  Sometimes, often, one is focal and one is moderator. However, sometimes neither/both are focal...</span>\n\n-----\n\n## Interactive Models: Sample Report\n\n*A sample brief report: Attitudes are focal, main effect and simple effects reported.*   \n\nWe analyzed birth control use in a General Linear Model with Positive Attitudes about Birth Control (ATT) and Negative Peer Pressure (PP) as quantitatively measured predictors. We also included the interaction between these two predictors in the model. We mean-centered all predictors.   \n\nThe overall model accounted for a significant amount of variance in Birth Control use, $R^2= 0.94, F(3,121) = 605.00, p < .001$.  The effect of ATT was significant, 95% CI(b) = [2.8, 3.2], $\\Delta R^2 = 0.56, t(121) = 33.00, p < .001$, such that birth control use increased by 3 units for every one unit increase in positive attitudes about birth control for participants who experienced average peer pressure (i.e., PP=3). However, PP significantly moderated the ATT effect on Birth Control, 95% CI(b)= [-1.1, -0.9], $\\Delta R^2 = 0.13, t(121) = 15.56, p < .001$, indicating that the magnitude of the ATT effect decreased for every one unit increase in PP (see Figure 1).  Despite this, the simple effects of ATT remained significant across meaningful levels of PP.  For example, the simple effect of ATT for participants who were experiencing high negative peer pressure (i.e., PP = 5) was significant, 95% CI(b)= [0.7, 1.3], $\\Delta R^2 = 0.02, t(121) = 6.35, p < .001$.  The simple effect of ATT for participants who were experiencing low negative peer pressure (PP=1) was also significant, 95% CI(b)= [4.7, 5.3], $\\Delta R^2 = 0.52, t(121)= 31.75, p < .001$.  \n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_pub <- expand.grid(att = 1:5, pp = c(2, 4))\npreds_pub_y <- predict(m_int, newdata = preds_pub, se.fit = TRUE) \n\npreds_pub <- preds_pub |> \n  bind_cols(preds_pub_y) |> \n  as_tibble() |>  \n  mutate(upper = fit + se.fit,\n         lower= fit - se.fit)\n\nplot_pub <- preds_pub |> \n  ggplot() +\n  geom_ribbon(aes(x = att, ymin = lower, ymax = upper, group = factor(pp)), \n              alpha = 0.4) +\n  geom_line(aes(x = att, y = fit, \n                color = factor(pp)), \n            linewidth = 1) +\n  labs(x = \"Attitude about Birth Control\",\n       y = \"Birth Control Use\",\n       color = \"Peer Pressure\") \n```\n:::\n\n\n-----\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_pub\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n-----\n\n## Two Quantitative Variables: Summary\n\nFor two quantitative IVs, you now know:   \n\n- How to quantify and test *main* effects (effect of IV at mean of other IV).   \n- How to quantify and test for interaction.   \n- How to quantify and test *simple* effects of each IV at levels of other IV.   \n- How to graphically display effects.    \n\nIn case it wasn’t obvious, this is the conceptual equivalent of a factorial ANOVA with two quantitative (rather than categorical) IVs.   \n",
    "supporting": [
      "10_interactions_two_quantitative_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}