---
title: "hw_09_shell" 
author: "TAs" 
date: "`r lubridate::today()`"
format: 
  html:
    toc: true 
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
---


## Part A: Reading Questions

### 1. Judd, McClelland, & Ryan talk of a “paradox” in using standardized residuals to detect outliers. Describe this paradox, present what the authors recommend using to solve it, and list the three reasons they recommend this solution. 




### 2. Of the assumptions of linear regression that refer to residuals, which two are the most problematic to violate in large samples? Why are these particularly concerning? What are solutions to violating these assumptions?




### 3. Explain the logic of a Q-Q plot and what normally distributed data would look like (about 3 sentences).





## Part B: Data Analysis

The data for this homework were adapted from a dataframe in the `car` package. You will be using the `hw_09_data.csv` data file provided to you.   

Each row in the data represents a country in the United Nations (`Country`). Infant mortality (`infantMortality`) is the rate of death in infancy among live births. Per capita GDP (`ppgdp`) is a measure of a country’s wealth that takes gross domestic product (GDP) and divides it by the number of people in the country. Both GDP and per capita GDP should be positive numbers. 

- `Country`: Name of the country (unique string variable)    
- `infantMortality`: Infant deaths/1000 live births	(range 1.92 – 124.53)   
- `ppgdp`: GDP per capita, in US dollars (range 114.8 – 105095.4)   


### 1. Explore the data! 
#### a. Read in the raw data and change the variable names to snake case.





#### b. Remove unrelated variables, keep only `infant_mortality`, `ppgdp`, and `country`.




#### c. Obtain descriptive statistics for numeric variables using `skim()` and `yank()`.




#### d. Create quick-and-dirty histograms of `infant_mortality` and `ppgdp`. 




#### e. There are two obvious outliers with invalid values on variable `infant_mortality` and `ppgdp`. Find them and assign NA to replace the invalid values.





#### f. Create quick-and-dirty histograms of `infant_mortality` and `ppgdp` once more. Are these variables normally distributed? If the variables are not normally distributed, would it always be a problem by itself? Why or why not? 





### 2. Conduct the following analysis **without** data transformation or case analysis.
#### a.	Fit a model to predict infant mortality from per capita GDP. 




#### b.	Report the results in one sentence, including relevant statistics. 




### 3. Check for violations of model assumptions.
#### a. Make a quick-and-dirty scatterplot of the relationship between infant mortality and per capita GDP. 




#### b. Create a Q-Q plot and density plot (using code from lab) to check for nomality. What are your conclusioins?





#### c. Plot the predicted values against the observed values (using code from lab) to check for constant variance. What are your conclusions?





#### d. Use `car::crPlots()` to check for linearity. What are your conclusions?




### 4. It turns out that the model assumptions were rather severely violated. So, let’s transform the variable(s). 

#### a. What is the suggested Box-Cox transformation? 




#### b. According to what you learned in lecture and lab, what might be a better transformation?


### 5. Log-transformation of the outcome variable.

#### a. Apply a log-transformation to `infant mortality` and create a quick-and-dirty histogram plot of your new variable.




#### b. Fit a new model with your transformed outcome. Summarize the results of the model in a sentence, including a practical interpretation of the coefficient. 



#### c. Check for violations of model assumptions again on the refitted model above. Did log-transforming infant mortality solve the problems? 




### 6. Log-transformation of the predictor variable.

#### a. Apply log-transformation to per capita GDP and refit the model to predict untransformed infant mortality. Summarize the results of this model, including a practical interpretation of the coefficient. 



#### b. Check for violations of model assumptions again on the refitted model above. Did log-transforming per capita GDP solve the problems?




### 7. Log-transformation of the outcome variable and the predictor variable.
#### a.	Fit a model where you use log-transformed per capita GDP to predict log-transformed infant mortality. Summarize the results of this model, including a practical interpretation of the coefficient.



#### b.	Check for violations of model assumptions again on the model you fit above. Did log-transforming both infant mortality and per capita GDP solve the problems?



### 8. Using the model you fit to answer question 7a, conduct a full case analysis. Specify which countried you would consider to have high leverage, to be model/regression outliers, to have excessive influence on the model as a whole, and to have excessive influence on the parameter estimate for log-transformed per capita GDP specifically.




### 9. Remove outlier(s).

#### a.	Remove any observations of countries which you think are outliers. 



#### b.	Justify why you removed the observation(s). How would it/they impact your conclusion regarding the relationship between infant mortality rate and per capita GDP, should it/they be kept in your model?



### 10. Refit the model you fit in 7a but with the outlier(s) removed. What changed in your results?





### 11.	Make two publication-quality graphs that show the effect of GDP on infant mortality, using the model you fit in question 10. In one graph, plot both the transformed variables [a linear relationship between log2(infant mortality) and log2(ppgdp)]. In the other graph, plot both the untransformed variables [a curvilinear relationship between infant mortality and ppgdp]. 




### 12.	Write a short paragraph reporting these results. Explain the transformation you made, and why you made it. Explain your case analysis, and why you chose to exclude the data that you did. Finally, interpret your model using all stats in APA format (i.e., report the effect of GDP on infant mortality, the F value, degrees of freedom, a variance-based effect size, and the p value).




### 13. How long did this week’s homework take you? 
