---
title: "hw_11_shell" 
author: "TAs" 
date: "`r lubridate::today()`"
format: 
  html:
    toc: true 
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
---


## Part A: Conceptual Questions

### 1.	What do Judd and colleagues recommend in terms of reporting *simple* and *main* effects? What is their justification? Does Jaccard (2003) agree or disagree with this perspective? 



### 2.	When should you dichotomize a continuous variable? Why?




### 3.	A researcher wants to determine if living in an urban versus rural area predicts anxiety. The researcher goes door to door in two towns (one urban and one rural) and asks all people living in each dwelling (home, apartment, etc.) questions to assess their anxiety. In multiple people live in the same dwelling, the researcher asks each of them to answer the questions. In two or three sentences, explain which model assumption is most directly violated by this research design.




## Part B: Data Analysis

Some researchers plan to examine whether alcohol consumption affects dart playing skills. Their study aims to explore the well-known placebo effect: if people believe they are consuming alcohol, or another drug, they may feel and behave as if they are actually under the influence of that substance when in reality they are not. Thus, the purpose of the study is to clarify whether it is the effect of alcohol or the expected effect of alcohol that leads to differences in performance.

Sixty dart players are invited to an open-bar event where dartboards are made available. Participants were randomly assigned to either receive real alcohol or a convincing placebo. Non-alcoholic placebos were piloted beforehand and shown to be indistinguishable from alcoholic beverages. Players reported their prior experience with dart games and self-assessed coordination (rated right before the game) to control for differences in dart playing ability and to monitor for interactions with the experimental manipulation. Performance scores during the study ranged from 0-150. Blood alcohol concentration (BAC) was also determined. BAC was multiplied by 100 in this dataset.

Researchers hypothesized that (1) there will be an effect of condition such that participants in the alcohol group would have lower game scores than those in the placebo group. Furthermore, the researchers hypothesized that (2) the effect of condition on game scores would be stronger for less experienced players. In addition, the researchers proposed to (3) conduct an exploratory analysis to examine whether blood alcohol concentration and self-rated coordination interacted to predict game scores.


**Codebook:**   

- `sub_id`: unique subject ID. (1 - 60) 
- `condition`: alcohol condition. (placebo; alcohol)    
- `experience`: prior experience with dart games. (novice; experienced)   
- `bac`: blood alcohol concentration * 100. (0 - 10)   
- `coordination`: self-assessed coordination. (0/poor - 10/good)   
- `score`: performance scores during the study. (63 - 150)   



### 1. Read in the data file (`hw_11_data.csv`), create centered versions of the four predictor variables (`condition`, `experience`, `coordination`, and `bac`), and explore univariate statistics and bivariate relationships.




### 2.	Make a table including the mean and standard deviation for score, coordination, and BAC broken down into the four possible combinations of condition and experience.





### 3. Does the effect of the alcohol condition on game scores depend on experience?

#### a.	Fit a model that addresses this question.




#### b.	Report and interpret each of the parameter estimates. Report F-value, and p-value for non-intercept estimates (one sentence each is sufficient).



#### c.	Describe the experience effect for those in the alcohol group. Use a general linear model with condition dummy coded for alcohol. Interpret the relevant coefficient and report an F-value and p-value.


#### d.	Create a publication quality graph depicting the first model that you fit.



### 4.	Fill in the blanks for this regression equation, recording your answers as A-D in your QMD document:
score = ___A___ + __B___ * condition_c + __C___ * experience_c + ___D____ * condition_c * experience_c



> A: 

> B: 

> C: 

> D: 


### 5.	Using the equation above, what is the magnitude of the effect of condition for novice participants? Try to find the answer from the equation above, without recoding your variables in R.





### 6.	Using the equation above, what is the magnitude of the effect of experience for participants in the alcohol condition? Try to find the answer from the equation above, without recoding your variables in R.





### 7.	Although this was not part of the researchers hypotheses, examine whether the effect of alcohol condition on game scores depended on coordination?

#### a.	Fit a model that addresses this question.



#### b.	Report and interpret each of the parameter estimates, reporting relevant statistics (one sentence each is sufficient).


#### c.	Determine the (simple) alcohol condition effect for someone with a coordination score one standard deviation above the mean of that variable. Interpret the relevant coefficient and report appropriate statistics.




### 8.	Using the b-value estimates obtained in question 7, write out the regression equation for the model you fit in 7a.




### 9.	What is the magnitude of the effect of coordination for participants in the placebo condition? Try to find the answer from the equation above, without recoding your variables in R.




### 10.	What is the expected score for participants with a coordination score of 9 who were in the placebo condition? Try to find the answer from the equation above, without recoding your variables in R.



### 11.	Does the effect of (measured) blood alcohol concentration on game scores depend on coordination?

#### a.	Fit a model that addresses this question.



#### b.	Report and interpret each of the parameter estimates, reporting relevant statistics (one sentence each is sufficient).


#### c.	Is there an effect of coordination for someone who has a BAC at the legal limit (coded as 8 in this data file)?





#### d.	Graph the model you ran in question 11a, with coordination on the x-axis. For BAC, plot two different regression lines: one representing participants with 0 BAC and the other representing the mean BAC among participants in the alcohol group. Bonus: Add a dotted vertical line at the mean of coordination. 




#### f.	Graph the model you ran in question 11a, with BAC on the x-axis. For coordination, plot two different regression lines: one representing participants 1 SD above the mean of coordination and the 1 SD below the mean. Bonus: Add a dotted line showing the effect of BAC on game scores for people at the mean of coordination.




###  12.	What would happen to the SE of the parameter estimate of the interaction term in the previous model if you had used the uncentered versions of blood alcohol concentration and coordination? Would it increase, decrease, stay the same, or is it impossible to say what will happen to it?




### 13.	Write up the results of the study and be explicit about whether the researchers’ 3 hypotheses were confirmed or not. There is no need to discuss the results from the model in question 7.




### 14.	How long did this assignment take you (in hours)?



