{
  "hash": "2747351fefd8bcab378bb1a3f6e96597",
  "result": {
    "engine": "knitr",
    "markdown": "# Unit 10: Inferences about Two Continuous Predictors and their Interaction\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Interactive Models: Two Quantitative Variables\n\n**Example:**   \n\nEffect of positive attitudes (1-5) about birth control and peer pressure to not use birth control (1-5) on intention to use birth control (0-30) among sexually active female adolescents.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(conflicts.policy = \"depends.ok\") \nlibrary(tidyverse)\nlibrary(broom)\nlibrary(patchwork)\nlibrary(skimr)\n\ntheme_set(theme_classic()) \n\npath_data <- \"data_lecture\"\n\ndata <- read_csv(here::here(path_data, \"10_interactions_birth_control.csv\"),\n                 show_col_types = FALSE) |> \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 125\nColumns: 4\n$ subid <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…\n$ att   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ pp    <dbl> 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5…\n$ bc    <dbl> 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4…\n```\n\n\n:::\n:::\n\n\n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  select(att:bc) |> \n  skim() |> \n  focus(n_missing, numeric.mean, numeric.sd, min = numeric.p0, max = numeric.p100) |> \n  yank(\"numeric\")\n```\n\n::: {.cell-output-display}\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| mean|   sd| min| max|\n|:-------------|---------:|----:|----:|---:|---:|\n|att           |         0|    3| 1.42|   1|   5|\n|pp            |         0|    3| 1.42|   1|   5|\n|bc            |         0|   11| 5.68|   3|  27|\n\n\n\n:::\n:::\n\n\n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  select(-subid) |> \n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     att   pp    bc\natt 1.00  0.0  0.75\npp  0.00  1.0 -0.50\nbc  0.75 -0.5  1.00\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n# Question\n\nIf you regressed BC on Att and PP in two separate linear models, what can you tell me about these two models based on the correlations above? \n:::\n\n:::{.fragment}\n[Regression coefficient for Att will be positive. Regression coefficient for PP will be negative. $R^2$ will be bigger for Att model ($R^2$ = .56) than for PP model ($R^2$ = .25).]{style=\"color:blue;\"}\n:::\n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_att <- lm (bc ~ att, data = data)\nm_pp <- lm (bc ~ pp, data = data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m_att)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     2.00     0.791      2.53 1.27e- 2\n2 att             3.00     0.239     12.6  7.92e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_att)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5625\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m_pp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     17.0     1.04      16.4  9.08e-33\n2 pp              -2       0.312     -6.40 2.91e- 9\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_pp)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.25\n```\n\n\n:::\n:::\n\n\n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  select(-subid) |> \n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     att   pp    bc\natt 1.00  0.0  0.75\npp  0.00  1.0 -0.50\nbc  0.75 -0.5  1.00\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n# Question\n\nBased on the correlations, what can you tell me about the model (parameter estimates and $R^2$) including both Att and PP as regressors?\n:::\n\n:::{.fragment}\n[The regression coefficients for Att and PP will match the coefficients from their respective bivariate models b/c Att and PP are fully orthogonal (uncorrelated). PP and Att each predict fully unique variance in BC.]{style=\"color:blue;\"}   \n\n[The $R^2$ for the additive model will be equal to the sum of the $R^2$s from the two bivariate models, again b/c Att and PP are orthogonal.]{style=\"color:blue;\"}\n:::\n\n-------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\n\nWhat about $\\eta_p^2$ for Att in the 1 predictor model vs. the 2 predictor model? Specify the augmented and compact models to test Att for 1 and 2 predictor approaches. Specify the formula for $\\eta_p^2$.\n:::\n\n:::{.fragment}\n[**Test for Att in 1 predictor model:**]{style=\"color:blue;\"}    \n[$BC_c = b_0 + 0*Att$]{style=\"color:blue;\"}    \n[$BC_a = b_0 + b_1*Att$]{style=\"color:blue;\"}    \n\n[**Test for Att in 2 predictor model:**]{style=\"color:blue;\"}    \n[$BC_c = b_0 + 0*Att + b_2*PP$]{style=\"color:blue;\"}    \n[$BC_a = b_0 + b_1*Att + b_2*PP$]{style=\"color:blue;\"}    \n\n[$\\eta_p^2 = \\frac{SSE_c - SSE_a}{SSE_c}$]{style=\"color:blue;\"}   \n\n- [Numerator is same for the both 1 and 2 predictor tests of Att.]{style=\"color:blue;\"}   \n- [Denominator is smaller for 2 predictor test.]{style=\"color:blue;\"}   \n- [Therefore, $\\eta_p^2$ for Att is bigger in 2 predictor model. Att produces a bigger proportional reduction in error.]{style=\"color:blue;\"}  \n- [Same would be true for PP]{style=\"color:blue;\"}  \n:::\n\n-------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\n\nWhat about $\\Delta R^2$ for Att in the 1 predictor model vs. the 2 predictor model? Specify the augmented and compact models to test Att for 1 and 2 predictor approaches. Specify the formula for $\\Delta R^2$.\n:::\n\n:::{.fragment}\n[**Test for Att in 1 predictor model:**]{style=\"color:blue;\"}    \n[$BC_c = b_0 + 0*Att$]{style=\"color:blue;\"}    \n[$BC_a = b_0 + b_1*Att$]{style=\"color:blue;\"}    \n\n[**Test for Att in 2 predictor model:**]{style=\"color:blue;\"}    \n[$BC_c = b_0 + 0*Att + b_2*PP$]{style=\"color:blue;\"}    \n[$BC_a = b_0 + b_1*Att + b_2*PP$]{style=\"color:blue;\"}    \n\n[$\\Delta R^2 = \\frac{SSE_c - SSE_a}{SSE_{mean-only}}$]{style=\"color:blue;\"}    \n\n[Numerator is same for the both 1 and 2 predictor tests of Att.]{style=\"color:blue;\"}   \n[Denominator is same for both 1 and 2 predictor tests.]{style=\"color:blue;\"}    \n[Therefore, $\\Delta R^2$ for Att does not change. Att explains the same proportion of **total** variance (error) in both models.]{style=\"color:blue;\"}     \n[Same would be true for PP]{style=\"color:blue;\"}     \n:::\n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_add <- lm(bc ~ att + pp, data = data)\ntidy(m_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     8.00     0.701      11.4 5.84e-21\n2 att             3.00     0.157      19.1 1.56e-38\n3 pp             -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n:::\n\n\n\n$BC = 8.0 + 3.0 * Att + -2.0*PP$   \n\n::: {.callout-important}\n# Question\n\nWhat has this model required (or what havent we tested for)?\n:::\n\n:::{.fragment}\n[It requires that the effect of each IV on the DV is constant across all levels/scores of the other IV.]{style=\"color:blue;\"}   \n\n[We have not allowed or tested for an interaction.]{style=\"color:blue;\"}\n:::\n\n-------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\n\nWhere are $b_{Att}, b_{PP},$ and $b_0$ in the figure below?\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npreds <- expand.grid(att = 1:5, pp = c(1, 3, 5))\npreds_y <- predict(m_add, newdata = preds)\n\nplot_m_add <- ggplot() +\n  geom_line(aes(x = preds$att, y = preds_y, color = factor(preds$pp)), \n            linewidth = 1) +\n  labs(x = \"Attitude about Birth Control\",\n       y = \"Birth Control Use\",\n       color = \"Peer Pressure\") \n\nplot_m_add\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n\n:::{.fragment}\n\n[$b_{Att}$ = slope of lines. Constant for all three lines.]{style=\"color:blue;\"}    \n[$b_{PP}$ = separation of lines. Lines are separated by $2*b_{PP}$. Constant across Att.]{style=\"color:blue;\"}    \n[$b_0$ = predicted value at Att = 0 and PP= 0. Not displayed in figure.]{style=\"color:blue;\"}\n:::\n\n-------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\n\nHow might we benefit from including a third regressor in the model to represent the interaction between Att and PP? Hint, there are two benefits.\n:::\n\n:::{.fragment}\n\n[1. If Att X PP effect is significant, it will increase $R^2$, decrease SEs, and therefore increase power to test all effects.]{style=\"color:blue;\"}    \n\n[2. If Att X PP is significant, it will provide us with a more complex, nuanced perspective on the nature of the Att and PP effects on BC.]{style=\"color:blue;\"}    \n\n**Definition: An interaction exists when the effect of 1 predictor on the DV differs across levels/values of the other predictor.**  \n:::\n\n-------------------------------------------------------------------------------\n\n- Regressors for interaction terms are calculated as the product of the regressors (for the predictors) in the interaction. In this case, we simply multiply Att X PP.   \n\n- You will typically want to **center** the $X$ in the primary model to yield tests of *main effects* of each $X$ as well as tests of the interaction (More on this as the slides develop).     \n\n- In R, you don’t need to actually compute the product term regressor directly. `A:B` in the `lm()` formula will include the A X B interaction regressor(s).    \n\n- `A*B` is further shorthand to include A, B, and A X B in the model.   \n\n- You should generally **not** include A X B in a model that does not include lower order effects (e.g., A, and B).    \n\n-------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\n\nWhat will change in the two predictor additive model if we center both $X$s?\n:::\n\n:::{.fragment}\n[1. $b_0$ and its SE will change. $b_0$ is the predicted value at 0 on all regressors in the model.]{style=\"color:blue;\"} [Advanced question: Will SE be bigger or smaller in centered model?]{style=\"color:red;\"}\n\n[2. $b_{Att}$ and $b_{PP}$ (and their SEs) will remain the same. The additive model forces the effect for each $X$ to be same across all values of other $X$s. Therefore, the effect of ATT is the same if PP = 0 or PP= 1, or PP=3, etc. Given this, centering PP does not change $b$ for ATT.]{style=\"color:blue;\"}         \n\n[3. Of course, $R^2$ also remains the same.]{style=\"color:blue;\"}\n:::\n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     8.00     0.701      11.4 5.84e-21\n2 att             3.00     0.157      19.1 1.56e-38\n3 pp             -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_add)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(att_c = att - mean(att),\n         pp_c = pp - mean(pp))\n\nm_add_c <- lm(bc ~ att_c + pp_c, data = data)\ntidy(m_add_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    11        0.222      49.6 1.01e-82\n2 att_c           3.00     0.157      19.1 1.56e-38\n3 pp_c           -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_add_c)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n\n\n-------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\n\nWhat will change when we add the interaction term (with centered $X$s) relative to the centered two predictor additive model?\n:::\n\n:::{.fragment}\n\n[1. An additional regressor will be included for Att x PP.]{style=\"color:blue;\"}    \n\n[2. If Att x PP accounts for DV variance, $R^2$ will increase and SEs for coefficients (and intercept) will be reduced.]{style=\"color:blue;\"}    \n\n[3. $b_0$ will remain the predicted value at 0 for all regressors. No change from centered two predictor additive model.]{style=\"color:blue;\"}    \n\n[4. $b_{Att}$ and $b_{PP}$ are respective effects at 0 on all other regressors. Including an interaction now allows for each $X$ effect to vary across levels/values of other $X$s.]{style=\"color:blue;\"}    \n\n[Thus, $b_{Att}$ is now the (*simple*) effect of Att at PP (centered) = 0 and the $b_{PP}$ is now the (*simple*) effect of PP at Att (centered) = 0.]{style=\"color:blue;\"} \n:::\n\n-------------------------------------------------------------------------------\n\n## Main Effects and Simple Effects\n\nIn ANOVA terms, The **Main Effect** of an IV is the overall effect of that IV on the DV averaging across the levels of the other IV(s) in the model.      \n\nA **Simple Effect** of an IV is the effect of that IV at a specific level of the other IV(s) in the model.     \n\nFrom this perspective, you can think about a main effect as a special simple effect where the specific level of the other IV is its average value.    \n\n-------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_c <- lm(bc ~ att_c * pp_c, data = data)\n\ntidy(m_int_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    11       0.129       85.6 4.33e-110\n2 att_c           3.00    0.0909      33.0 2.41e- 62\n3 pp_c           -2.00    0.0909     -22   4.16e- 44\n4 att_c:pp_c     -1       0.0643     -15.6 1.20e- 30\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_int_c)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9375\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m_add_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    11        0.222      49.6 1.01e-82\n2 att_c           3.00     0.157      19.1 1.56e-38\n3 pp_c           -2.00     0.157     -12.8 3.39e-24\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_add_c)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n\n\n-------------------------------------------------------------------------------\n\n$BC = 11.0 + 3.0 * Att_c + -2.0*PP_c$    \n\n$BC = 11.0 + 3.0 * Att_c + -2.0*PP_c + -1.0*Att_c*PP_c$     \n\n::: {.callout-important}\n# Exercise\n\nLink intercepts and coefficients from each model to their respective figures.\n:::\n\n*Note:* figures use raw (not centered) predictors. Means for both predictors are 3.  \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------------\n\n$BC = 11.0 + 3.0 * Att_c + -2.0*PP_c + -1.0*Att_c*PP_c$     \n\n::: {.callout-important}\n# Question\n\nQuestion: What would the interactive model look like if we hadn’t centered each IV?\n:::\n\n:::{.fragment}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int <- lm(bc ~ att * pp, data = data) \ntidy(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -1.00    0.707      -1.41 1.60e- 1\n2 att             6.00    0.213      28.1  6.17e-55\n3 pp              1       0.213       4.69 7.23e- 6\n4 att:pp         -1       0.0643    -15.6  1.20e-30\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(m_int)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9375\n```\n\n\n:::\n:::\n\n\n\n:::\n\n------------------------------------------------------------------------------\n\n$BC = 11.0 + 3.0 * Att_c + -2.0*PP_c + -1.0*Att_c*PP_c$ \n\n$BC = -1.0 + 6.0 * Att + 1.0*PP + -1.0*Att*PP$   \n\n::: {.callout-important}\n# Exercise\n\nLink intercept and coefficients from the raw model to the expanded figure below on right.\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------------\n\n$BC = 11.0 + 3.0 * Att_c + -2.0*PP_c + -1.0*Att_c*PP_c$ \n\n$BC = -1.0 + 6.0 * Att + 1.0*PP + -1.0*Att*PP$    \n\n::: {.callout-important}\n# Question\n\nSo what does $b_{Att*PP}$ indicate?\n:::\n\n:::{.fragment}\n[The coefficient for the interaction indicates how the simple effect of each $X$ changes for a one unit increase on the other $X$.]{style=\"color:blue;\"}    \n\n**The interaction coefficient applies symmetrically to the effects of both $X$s.**\n:::\n\n-----\n\nConsidering Att in raw model:   \n\n- Att effect is 6 for PP = 0    \n- Att effect is 5 for PP = 1    \n- Att effect is 4 for PP = 2    \n- Att effect is 3 for PP = 3   \n- Att effect is 2 for PP = 4   \n- Att effect is 1 for PP = 5    \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_m_int_expanded\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\n\n-----\n\nConsidering PP in raw model:   \n\n- PP effect is 1 for Att = 0   \n- PP effect is 0 for Att = 1    \n- PP effect is -1 for Att = 2    \n- PP effect is -2 for Att = 3    \n- PP effect is -3 for Att = 4    \n- PP effect is -4 for Att = 5     \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_m_int_expanded\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n\n-----\n\n## Interactive Models: Coefficient Magnitudes\n\n- Interaction and its test is obtained from any model (regardless of centering).    \n\n- *Main* effects of IVs are obtained from model with all IVs centered on mean. You may or may not choose to report these main effects depending on the situation.     \n\n- Magnitude of *simple* effects of either IV can be calculated directly from the raw or centered model (I prefer the raw model for ease of thinking in raw units). <span style=\"color: red;\">How?</span>\n\n-----\n\n## Interactive Models: Raw Model Coefficients\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int <- lm(bc ~ att * pp, data = data) \nbroom::tidy(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -1.00    0.707      -1.41 1.60e- 1\n2 att             6.00    0.213      28.1  6.17e-55\n3 pp              1       0.213       4.69 7.23e- 6\n4 att:pp         -1       0.0643    -15.6  1.20e-30\n```\n\n\n:::\n:::\n\n\n\n-----\n\n## Interactive Models: Simple Effect Magnitudes\n\nMagnitude of *simple* effects of either IV can be calculated directly from the raw or centered model (I prefer the raw model for ease of thinking in raw units). \n\n::: {.callout-important}\n# Question\n\nHow?\n:::\n\n$BC = -1.0 + 6.0 * Att + 1.0*PP + -1.0*Att*PP$   \n\n:::{.fragment}\n\n[Effect of Att = 6.0 + -1.0 * PP]{style=\"color:blue;\"}    \n\n[Effect of PP = 1.0 + -1.0 * Att]{style=\"color:blue;\"}    \n:::\n\n----\n\n::: {.callout-important}\n# Question\n\nHow could you obtain formal significance tests for any specific simple effects (e.g., effect of Att at PP = 1, 3, & 5)?\n:::\n\n:::{.fragment}\n\n$BC = -1.0 + 6.0 * Att + 1.0*PP + -1.0*Att*PP$    \n\n[Effect of Att = 6.0 + -1.0 * PP]{style=\"color:blue;\"}   \n\n[Effect of Att = 6.0 + -1.0 * (1) = 5]{style=\"color:blue;\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(pp_1 = pp - 1)\n\nm_pp_1 <- lm(bc ~ att * pp_1, data = data)\nbroom::tidy(m_pp_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) -2.54e-14    0.522  -4.87e-14 1.00e+ 0\n2 att          5.00e+ 0    0.157   3.18e+ 1 1.57e-60\n3 pp_1         1.00e+ 0    0.213   4.69e+ 0 7.23e- 6\n4 att:pp_1    -1.00e+ 0    0.0643 -1.56e+ 1 1.20e-30\n```\n\n\n:::\n:::\n\n\n\n:::\n\n-----\n\n\n$BC = -1.0 + 6.0 * Att + 1.0*PP + -1.0*Att*PP$   \n\n[Effect of Att = 6.0 + -1.0 * PP]{style=\"color:blue;\"}       \n\n[Effect of Att = 6.0 + -1.0 * (5) = 1]{style=\"color:blue;\"}    \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(pp_5 = pp - 5)\n\nm_pp_5 <- lm(bc ~ att * pp_5, data = data)\nbroom::tidy(m_pp_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     4.00    0.522       7.66 5.12e-12\n2 att             1.00    0.157       6.35 3.91e- 9\n3 pp_5            1.00    0.213       4.69 7.23e- 6\n4 att:pp_5       -1       0.0643    -15.6  1.20e-30\n```\n\n\n:::\n:::\n\n\n\n-----\n\n## Interactive Models: Reporting Considerations\n\n::: {.callout-important}\n# Question\n\nSo what do you report and in what order?\n:::\n\n\n:::{.fragment}\n[There is no one answer here. Some say you never report main effects when there are significant interactions. This camp would say, report only interaction and possibly simple effects.]{style=\"color:blue;\"}   \n\n[Others (including me) believe that main effects are sometimes useful to report even when interaction is significant. *Main* effects (effect at “mean” of other IV) provides an anchor for effect. The interaction then indicates how this effect changes across values of the other IV. *Simple* effects can sometimes allow you to describe further how this effect changes at various values of other IV.]{style=\"color:blue;\"}    \n\n[The other complexity surrounds the nature of the two IVs.  Sometimes, often, one is focal and one is moderator. However, sometimes neither/both are focal…]{style=\"color:blue;\"}    \n:::\n\n-----\n\n## Interactive Models: Sample Report\n\n*A sample brief report: Attitudes are focal, main effect and simple effects reported.*   \n\nWe analyzed birth control use in a General Linear Model with Positive Attitudes about Birth Control (ATT) and Negative Peer Pressure (PP) as quantitatively measured predictors. We also included the interaction between these two predictors in the model. We mean-centered all predictors.   \n\nThe overall model accounted for a significant amount of variance in Birth Control use, $R^2= 0.94, F(3,121) = 605.00, p < .001$.  The effect of ATT was significant, 95% CI(b) = [2.8, 3.2], $\\Delta R^2 = 0.56, t(121) = 33.00, p < .001$, such that birth control use increased by 3 units for every one unit increase in positive attitudes about birth control for participants who experienced average peer pressure (i.e., PP=3). However, PP significantly moderated the ATT effect on Birth Control, 95% CI(b)= [-1.1, -0.9], $\\Delta R^2 = 0.13, t(121) = 15.56, p < .001$, indicating that the magnitude of the ATT effect decreased for every one unit increase in PP (see Figure 1).  Despite this, the simple effects of ATT remained significant across meaningful levels of PP.  For example, the simple effect of ATT for participants who were experiencing high negative peer pressure (i.e., PP = 5) was significant, 95% CI(b)= [0.7, 1.3], $\\Delta R^2 = 0.02, t(121) = 6.35, p < .001$.  The simple effect of ATT for participants who were experiencing low negative peer pressure (PP=1) was also significant, 95% CI(b)= [4.7, 5.3], $\\Delta R^2 = 0.52, t(121)= 31.75, p < .001$.  \n\n-----\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_pub <- expand.grid(att = 1:5, pp = c(2, 4))\npreds_pub_y <- predict(m_int, newdata = preds_pub, se.fit = TRUE) \n\npreds_pub <- preds_pub |> \n  bind_cols(preds_pub_y) |> \n  as_tibble() |>  \n  mutate(upper = fit + se.fit,\n         lower= fit - se.fit)\n\nplot_pub <- preds_pub |> \n  ggplot() +\n  geom_ribbon(aes(x = att, ymin = lower, ymax = upper, group = factor(pp)), \n              alpha = 0.4) +\n  geom_line(aes(x = att, y = fit, \n                color = factor(pp)), \n            linewidth = 1) +\n  labs(x = \"Attitude about Birth Control\",\n       y = \"Birth Control Use\",\n       color = \"Peer Pressure\") \n```\n:::\n\n\n\n-----\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_pub\n```\n\n::: {.cell-output-display}\n![](10_interactions_two_quantitative_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n\n\n-----\n\n## Two Quantitative Variables: Summary\n\nFor two quantitative IVs, you now know:   \n\n- How to quantify and test *main* effects (effect of IV at mean of other IV).   \n- How to quantify and test for interaction.   \n- How to quantify and test *simple* effects of each IV at levels of other IV.   \n- How to graphically display effects.    \n\nIn case it wasn’t obvious, this is the conceptual equivalent of a factorial ANOVA with two quantitative (rather than categorical) IVs.   \n",
    "supporting": [
      "10_interactions_two_quantitative_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}