---
title: "hw_07_shell" 
author: "TAs" 
date: "`r lubridate::today()`"
format: 
  html:
    toc: true 
    toc_depth: 2
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

# Reading Questions

## 1. 
What does it mean to have "redundancy between predictors" in multiple regression? What is the consequence of having redundant predictors? Answer in 2-3 sentences.



# Data Analysis

Does childhood cognitive ability predict the size of developing brains? A team of neuroscientists recruited a longitudinal sample of 40 participants to answer this question. When the participants reached age 12, the researchers administered the fifth edition of Wechsler Intelligence Scale for Children (WISC-V) to assess childhood cognitive ability. When the participants aged 21, the researchers obtained structural MRI scans of the participants’ brains and calculated total MRI voxel count as a measure of brain size. Because body size and sex are known to relate to brain size, the neuroscientist also asked the participants to report their height and weight at age 21, as well as their sex assigned at birth. 

You were asked to conduct the statistical analyses to test the hypothesis that childhood cognitive ability is positively associated with brain size in adulthood.

Tragically, the data files came in a total mess. They do not have proper file extensions, so you do not know their exact file type, apart from the fact that they are regular delimited text files. The data files also do not have proper variable names labeled. Luckily, your colleague was able to provide you with the codebooks of the two datafiles: `hw_07_iq` and `hw_07_brain`.

**Codebook for `iq`**

- `subject_id`:	Subject ID number	(range 1 - 40)
- `simi`:	WISC-V subtest score: Similarities (range 5 - 20)
- `voca`:	WISC-V subtest score: Vocabulary	(range 5 - 20)
- `bloc`:	WISC-V subtest score: Block Design	(range 5 - 20)
- `matr`:	WISC-V subtest score: Matrix Reasoning	(range 5 - 20)
- `figr`:	WISC-V subtest score: Figure Weights	(range 5 - 20)
- `digi`:	WISC-V subtest score: Digit Span	(range 5 - 20)
- `code`:	WISC-V subtest score: Coding	(range 5 - 20)

**Codebook for `brain`**

- `subject_id`:	Subject ID number	(range 1 - 40)
-	`sex`: Sex assigned at birth. (0 = female, 1  = male)
-	`weight`:	Weight in pounds	(range 106 - 192)
-	`height`:	Height in inches	(range 62 - 77)
-	`mri_count`: Total voxel count from 18 slices, in thousands (range 790.62 – 1079.55)
-	`openness`:	Big-five inventory: Openness (in adulthood)	(range -1.65 - 2.17)



## 1. 
Read in both data files (hw_07_iq and hw_07_brain) using a function within the `readr` pacakge (this is one of the packages in the tidyverse that is loaded with `library(tidyverse)`.  You might need to view the text file directly (in a text editor) and then read a bit to figure out what function to use.   [This cheatsheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_data-import.pdf) might help some! 




## 2. 
For both dataframes, rename the columns according to the codebook so that the column names are meaningful variable names.





## 3. 
Use the `full_join()` function from the dplyr package to combine the two dataframes, so that you end up with one dataframe that contains all subjects and all variables needed for the analyses.  You may need to read the help on this function to understand how it works.  Make sure to check that the join worked correctly.


## 4. 
The raw data contain 7 subtest scores from WISC-V, measuring different domains of cognitive functioning. These subtest scores are meant to be added up into a Full-Scale Intelligence Quotient (FSIQ) that measures overall cognitive ability. Use `var_score()` to compute `fsiq`. If done correctly, `fisq` would have a mean of around 100 and a standard deviation of roughly 15.





## 5.	
Make a correlation/scatterplot matrix of the following variables: `mri_count`, `sex`, `weight`, `height` and `fsiq` (Hint: consider using the `GGally` package).






## 6.	
Report the three strongest correlations among these variables.



## 7.	
Fit a 2-parameter model, where `fsiq` alone predicts total voxel count (`mri_count`). Report the parameter estimate for `fsiq`.  Also report an appropriate variance based effect size estimate for `fsiq`. Test the null hypothesis that this parameter estimate is 0 using both of the methods you know (t-test of parameter estimate AND model comparison of appropriate compact and augmented models).  Report the appropriate information for each of these statistical tests (NOTE: Of course, in real life you would choose only one of these two statistical tests because they are statistically equivalent!  This is just for practice).  




## 8. 
Now fit a 5-parameter model predicting total voxel count (`mri_count`) from `fsiq`, `sex`, `height`, and `weight`. Report the statistical test and interpret the parameter estimate corresponding to the focal predictor. Also compute its PRE. How did PRE for `fsiq` change from PRE in the 2-parameter model? Why?






## 9. 
Use a function we learned in lab to check for multicollinearity between your predictors in the 5-parameter model. Is multicollinearity a problem? How do you know?




## 10.	
Create a publication-quality graph that represents total voxel count (in thousands) as a function of FSIQ, when holding height and weight constant at their means and sex constant at the center of its coding scheme. Your plot should include 95% confidence interval bands around the point estimates, raw data points, and informative axis labels.





## 11. 
Indicate the number of hours spent on this assignment.
