{
  "hash": "d6c9d8a9fd38f71235646c821f397389",
  "result": {
    "engine": "knitr",
    "markdown": "# Unit 11: Inferences about a Continuous and Dichotomous Predictor and their Interaction\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n## Interactive Models: Quantitative and Dichotomous\n\n**Example:**    \n\nEffect of juror implicit bias (0 - 100) and race of defendant (White = 0; Black = 1) on ratings of defendant guilt (0 - 100).\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\noptions(conflicts.policy = \"depends.ok\") \nlibrary(tidyverse)\nlibrary(broom)\nlibrary(patchwork)\nlibrary(skimr)\n\ntheme_set(theme_classic()) \n\npath_data <- \"data_lecture\"\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsse <- function(model) {\n  sum(residuals(model)^2)\n}\n\npre <- function(compact, augmented) {\n  sse_c <- sse(compact)\n  sse_a <- sse(augmented)\n  (sse_c - sse_a)/sse_c\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(here::here(path_data, \"11_interactions_jurors.csv\"),\n                 show_col_types = FALSE) |> \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 240\nColumns: 4\n$ subid        <chr> \"001\", \"002\", \"003\", \"004\", \"005\", \"006\", \"007\", \"008\", \"…\n$ black_defend <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ bias         <dbl> 42.53833, 52.55506, 57.25757, 46.99403, 52.21168, 18.8001…\n$ guilt        <dbl> 40.83539, 44.44454, 47.90421, 57.45485, 62.45751, 18.2372…\n```\n\n\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  skim(black_defend:guilt) |> \n  focus(n_missing, numeric.mean, numeric.sd, \n        min = numeric.p0, max = numeric.p100) |> \n  yank(\"numeric\")\n```\n\n::: {.cell-output-display}\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing|  mean|    sd|   min|   max|\n|:-------------|---------:|-----:|-----:|-----:|-----:|\n|black_defend  |         0|  0.50|  0.50|  0.00|  1.00|\n|bias          |         0| 34.68| 16.15|  3.86| 63.33|\n|guilt         |         0| 43.79| 18.09| 16.66| 93.37|\n\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n# Question\nHow do you conduct an ANCOVA analysis in regression using bias as a covariate?\n:::\n\n:::{.fragment}\n[Regress guilt on defendant race and bias in an additive model. Test & interpret the defendant race effect.]{style=\"color:blue;\"}\n:::\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_add <- lm(guilt ~ black_defend + bias, data = data)\n\nm_add |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    11.8      2.02        5.84 1.71e- 8\n2 black_defend    8.50     1.56        5.45 1.28e- 7\n3 bias            0.799    0.0484     16.5  2.83e-41\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(m_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %   97.5 %\n(Intercept)  7.8288544 15.79898\nblack_defend 5.4267932 11.57569\nbias         0.7039293  0.89468\n```\n\n\n:::\n:::\n\n\n\n$\\eta_p^2$ for defendant race \n\n\n::: {.cell}\n\n```{.r .cell-code}\npre(lm(guilt ~ bias, data), m_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1112738\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n# Question\nWhat do we conclude? What do we report?\n:::\n\n:::{.fragment}\n:::: {.callout-important}\n# Question\nWhat is the specific interpretation in terms of the effect of defendant race?\n::::\n:::\n\n:::{.fragment}\n[On average, Black defendants are judged to be 8.5 units more guilty than White defendants, controlling for (holding constant) implicit bias.]{style=\"color:blue;\"}   \n\n:::: {.callout-important}\n# Question \nWhat does this model require with respect to this group comparison across various levels of implicit bias?\n::::\n:::\n\n:::{.fragment}\n[It requires that the magnitude of the Black defendant (vs. White defendant) group difference ($b=8.5$) be the same for all levels of implicit bias **and** the bias effect be the same for both defendant races.]{style=\"color:blue;\"}\n:::\n\n--------------------------------------------------------------------------------\n\n::: {.callout-important}\n# Question\nHow can you remove that constraint?\n:::\n\n:::{.fragment}\n[Include an interaction between defendant race and bias.]{style=\"color:blue;\"}    \n\n:::: {.callout-important}\n# Question\nBut what is now important to do with $X$s?\n::::\n:::\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(black_defend_c = if_else(black_defend == 0, -.5, .5),\n         bias_c = bias - mean(bias))\n```\n:::\n\n\n\nAlways check that your transformations work as expected (mean, min, max, N, exemplar values).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice_head(data, n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  subid black_defend  bias guilt black_defend_c bias_c\n  <chr>        <dbl> <dbl> <dbl>          <dbl>  <dbl>\n1 001              0  42.5  40.8           -0.5   7.86\n2 002              0  52.6  44.4           -0.5  17.9 \n3 003              0  57.3  47.9           -0.5  22.6 \n4 004              0  47.0  57.5           -0.5  12.3 \n5 005              0  52.2  62.5           -0.5  17.5 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  pivot_longer(c(black_defend_c, bias_c), names_to = \"var\") |> \n  group_by(var) |> \n  summarise(mean = mean(value), \n            sd = sd(value), \n            min = min(value), \n            max = max(value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  var                 mean     sd   min   max\n  <chr>              <dbl>  <dbl> <dbl> <dbl>\n1 bias_c         -1.97e-15 16.2   -30.8  28.7\n2 black_defend_c  0         0.501  -0.5   0.5\n```\n\n\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int <- lm(guilt ~ black_defend_c * bias_c, data = data)\n\nm_int |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                  estimate std.error statistic   p.value\n  <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)             43.9      0.751      58.4  2.78e-142\n2 black_defend_c           8.50     1.50        5.66 4.40e-  8\n3 bias_c                   0.797    0.0466     17.1  3.24e- 43\n4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           2.5 %     97.5 %\n(Intercept)           42.3761677 45.3354438\nblack_defend_c         5.5405532 11.4591055\nbias_c                 0.7054229  0.8890371\nblack_defend_c:bias_c  0.2312938  0.5985222\n```\n\n\n:::\n:::\n\n\n\n$\\eta_p^2$ for interaction between bias and defendant race (centered)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre(lm(guilt ~ black_defend_c + bias_c, data), m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07746803\n```\n\n\n:::\n:::\n\n\n\n$\\eta_p^2$ for bias (centered)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre(lm(guilt ~ black_defend_c + bias_c:black_defend_c, data), m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5535959\n```\n\n\n:::\n:::\n\n\n\n$\\eta_p^2$ for defendant race (centered)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre(lm(guilt ~ bias_c + bias_c:black_defend_c, data), m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1194663\n```\n\n\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n**Additive Model:**   \n\n$\\text{guilt} = 11.8 + 8.5*\\text{black defend} + 0.8*\\text{bias}$\n\n\n**Interactive Model:**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n\n[Link model coefficients to each figure.]{style=\"color:red;\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npreds_add <- expand.grid(bias = seq(3, 65, by = 1), black_defend = c(0, 1))\npreds_y_add <- predict(m_add, newdata = preds_add, se.fit = TRUE) \n\nplot_add <- preds_add |> \n  bind_cols(preds_y_add) |> \n  as_tibble() |>  \n  mutate(upper = fit + se.fit,\n         lower= fit - se.fit) |> \n  ggplot() +\n  geom_ribbon(aes(x = bias, ymin = lower, ymax = upper, \n                  group = factor(black_defend, \n                                 levels = c(0,1),\n                                 labels = c(\"White\", \"Black\"))), \n              alpha = 0.4) +\n  geom_line(aes(x = bias, y = fit, \n                color = factor(black_defend, \n                                 levels = c(0,1),\n                                 labels = c(\"White\", \"Black\"))), \n            linewidth = 1) +\n  labs(x = \"Juror Implicit Bias\",\n       y = \"Defendant Guilt\",\n       color = \"Defendant Race\") \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nm_int_raw <- lm(guilt ~ black_defend * bias, data = data)\npreds_int <- expand.grid(bias = seq(3, 65, by = 1), black_defend = c(0, 1))\npreds_y_int <- predict(m_int_raw, newdata = preds_int, se.fit = TRUE) \n\npreds_int <- preds_int |> \n  bind_cols(preds_y_int) |> \n  as_tibble() |>  \n  mutate(upper = fit + se.fit,\n         lower= fit - se.fit)  \n\nplot_int <- ggplot() +\n  geom_ribbon(aes(x = preds_int$bias, ymin = preds_int$lower, ymax = preds_int$upper, \n                  group = factor(preds_int$black_defend, \n                                 levels = c(0, 1),\n                                 labels = c(\"White\", \"Black\"))), \n              alpha = 0.4) +\n  geom_line(aes(x = preds_int$bias, y = preds_int$fit, \n                color = factor(preds_int$black_defend, \n                                 levels = c(0, 1),\n                                 labels = c(\"White\", \"Black\"))), \n            linewidth = 1) +\n  labs(x = \"Juror Implicit Bias\",\n       y = \"Defendant Guilt\",\n       color = \"Defendant Race\") \n\nplot_add + plot_int\n```\n\n::: {.cell-output-display}\n![](11_interactions_quantitative_and_dichotomous_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n## Quantitative & Dichotomous: Predictor *Main* effects\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                  estimate std.error statistic   p.value\n  <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)             43.9      0.751      58.4  2.78e-142\n2 black_defend_c           8.50     1.50        5.66 4.40e-  8\n3 bias_c                   0.797    0.0466     17.1  3.24e- 43\n4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n\n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n::: {.callout-important}\n# Question\nWhat is the interpretation of $b= 0.8$ for bias (centered)?\n:::\n\n:::{.fragment}\n[This is the unweighted effect of bias averaged across White and Black defendants.]{style=\"color:blue;\"}       \n\n[You can think about this like a main effect in ANOVA. For every one unit increase in bias, ratings of defendants’ guilt increased by 0.8 units when averaging across defendants of both races (holding constant race at its unweighted average), $t(236)= 17.1, p < .001$.]{style=\"color:blue;\"}    \n\nYou should also describe the effect with the 95% CI for $b$ and a variance effect size estimate.\n:::\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npreds_effect_bias <- predict(m_int_raw, \n                             newdata = tibble(black_defend = .5,\n                                              bias = seq(3, 65, by = 1)), \n                             se.fit = TRUE) |> \n  as_tibble() |> \n  bind_cols(tibble(black_defend = .5, bias = seq(3, 65, by = 1))) \n\nplot_int <- plot_int +\n  geom_line(aes(x = preds_effect_bias$bias,\n                y = preds_effect_bias$fit), \n            linewidth = .75)\n\nplot_int\n```\n\n::: {.cell-output-display}\n![](11_interactions_quantitative_and_dichotomous_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                  estimate std.error statistic   p.value\n  <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)             43.9      0.751      58.4  2.78e-142\n2 black_defend_c           8.50     1.50        5.66 4.40e-  8\n3 bias_c                   0.797    0.0466     17.1  3.24e- 43\n4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n\n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n::: {.callout-important}\n# Question\nWhat is the interpretation of $b= 8.5$ for defendant race (centered)?\n:::\n\n:::{.fragment}\n[This is the effect of defendant race for participants of average implicit bias. You can think about this like a main effect in ANOVA.]{style=\"color:blue;\"}      \n\n[Black defendants are rated 8.5 units more guilty than White defendants among jurors with average bias (holding constant bias at its mean), $t(236) = 5.66, p < .001$.]{style=\"color:blue;\"}     \n\nYou should also describe the effect with the 95% CI for $b$ and a variance effect size estimate.  \n:::\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_int <- plot_int +\n  geom_vline(xintercept = mean(data$bias), linewidth = .75)\n\nplot_int\n```\n\n::: {.cell-output-display}\n![](11_interactions_quantitative_and_dichotomous_files/figure-revealjs/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                  estimate std.error statistic   p.value\n  <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)             43.9      0.751      58.4  2.78e-142\n2 black_defend_c           8.50     1.50        5.66 4.40e-  8\n3 bias_c                   0.797    0.0466     17.1  3.24e- 43\n4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n\n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n::: {.callout-important}\n# Question\nHow do we test for the interaction between Bias and Defendant Race on Guilt?\n:::\n\n:::{.fragment}\n[The test of the $b$ for the product term (defendant race X bias) is the test of the interaction. It is significant, $t(236)= 4.45, p< .001$.]{style=\"color:blue;\"}     \n:::\n\n:::{.fragment}\n:::: {.callout-important}\n# Question\nWhat does this mean to have an interaction and how do you interpret $b = 0.4$?\n::::\n:::\n\n:::{.fragment}\n[The magnitude of the effect of defendant race on guilt increases by 0.4 units for every one unit increase in bias.]{style=\"color:blue;\"}     \n\n[The magnitude of the effect of bias is 0.4 units greater when the defendants are Black than when they are White.]{style=\"color:blue;\"}    \n:::\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_int\n```\n\n::: {.cell-output-display}\n![](11_interactions_quantitative_and_dichotomous_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n\n\n- The slopes of the lines differ by 0.4 **or**  \n\n- The separation of the lines increases by 0.4 for every 1 unit increase in bias.\n\n--------------------------------------------------------------------------------\n\n## Quantitative & Dichotomous: Predictor *simple* effects\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                  estimate std.error statistic   p.value\n  <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)             43.9      0.751      58.4  2.78e-142\n2 black_defend_c           8.50     1.50        5.66 4.40e-  8\n3 bias_c                   0.797    0.0466     17.1  3.24e- 43\n4 black_defend_c:bias_c    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n\n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n::: {.callout-important}\n# Question\nHow do you quantify and test the simple effects of bias, separately for White and Black defendants? What are these two simple effects on the previous figure?\n:::\n\n:::{.fragment}\n[Simple effects of bias are represented as the slopes of the two lines.]{style=\"color:blue;\"}    \n[Fit two interactive models with dummy coding for defendant race - one with White = 0 for **White** simple effect and one with Black = 0 for **Black** simple effect.]{style=\"color:blue;\"}     \n\n[In each of these models, $b$ for bias will be the simple effect for group coded as 0.]{style=\"color:blue;\"}    \n:::\n\n:::{.fragment}\n::::{.callout-important}\n# Question\nWhat should the coefficients be (think about it)?\n::::\n:::\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_white <- lm(guilt ~ black_defend * bias_c, data = data)\n\nm_white |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                estimate std.error statistic   p.value\n  <chr>                  <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)           39.6      1.06       37.3  6.72e-101\n2 black_defend           8.50     1.50        5.66 4.40e-  8\n3 bias_c                 0.590    0.0662      8.90 1.46e- 16\n4 black_defend:bias_c    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(white_defend = 1 - black_defend)\n\nm_black <- lm(guilt ~ white_defend * bias_c, data = data)\n\nm_black |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                estimate std.error statistic   p.value\n  <chr>                  <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)           48.1      1.06       45.3  2.20e-118\n2 white_defend          -8.50     1.50       -5.66 4.40e-  8\n3 bias_c                 1.00     0.0656     15.3  3.01e- 37\n4 white_defend:bias_c   -0.415    0.0932     -4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n**Centered model**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Dummy, White = 0**   \n$\\text{guilt} = 39.6 + 8.5*\\text{black defend} + 0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \n\n**Dummy, Black = 0**   \n$\\text{guilt} = 48.1 + -8.5*\\text{white defend} + 1.0*\\text{bias}_c + -.4*\\text{white defend}*\\text{bias}_c$   \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of the intercept in each model?\n:::\n\n:::{.fragment}\n[Centered: Predicted guilt rating unweighted across defendant race for juror of average bias.]{style=\"color:blue;\"}      \n\n[Dummy/White as 0: Predicted guilt rating for White defendant for juror of average bias.]{style=\"color:blue;\"}     \n\n[Dummy/Black as 0: Predicted guilt rating for Black defendant for juror of average bias.}{style=\"color:blue;\"}    \n:::\n\n--------------------------------------------------------------------------------\n\n**Centered model**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Dummy, White = 0**   \n$\\text{guilt} = 39.6 + 8.5*\\text{black defend} + 0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \n\n**Dummy, Black = 0**   \n$\\text{guilt} = 48.1 + -8.5*\\text{white defend} + 1.0*\\text{bias}_c + -.4*\\text{white defend}*\\text{bias}_c$   \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of $b$ for defendant race in each model?\n:::\n\n:::{.fragment}\n[Centered: The contrast of mean guilt ratings for Black vs. White defendants for jurors of average bias.]{style=\"color:blue;\"}    \n\n[Dummy/White as 0: The contrast of mean guilt ratings for Black vs. White defendants for jurors of average bias.]{style=\"color:blue;\"}      \n\n[Dummy/Black as 0: The contrast of mean guilt ratings for White vs. Black defendants for jurors of average bias.]{style=\"color:blue;\"}    \n:::\n\n--------------------------------------------------------------------------------\n\n**Centered model**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Dummy, White = 0**   \n$\\text{guilt} = 39.6 + 8.5*\\text{black defend} + 0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \n\n**Dummy, Black = 0**   \n$\\text{guilt} = 48.1 + -8.5*\\text{white defend} + 1.0*\\text{bias}_c + -.4*\\text{white defend}*\\text{bias}_c$   \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of $b$ for bias in each model?\n:::\n\n:::{.fragment}\n[Centered: The change in guilt for a 1 unit increase in bias, unweighted/averaged across defendant race.]{style=\"color:blue;\"}      \n\n[Dummy/White as 0: The change in guilt for a 1 unit increase in bias for White defendants.]{style=\"color:blue;\"}      \n\n[Dummy/Black as 0: The change in guilt for a 1 unit increase in bias for Black defendants.]{style=\"color:blue;\"}    \n:::\n\n--------------------------------------------------------------------------------\n\n**Centered model**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Dummy, White = 0**   \n$\\text{guilt} = 39.6 + 8.5*\\text{black defend} + 0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \n\n**Dummy, Black = 0**   \n$\\text{guilt} = 48.1 + -8.5*\\text{white defend} + 1.0*\\text{bias}_c + -.4*\\text{white defend}*\\text{bias}_c$   \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of $b$ for product term in each model (from a bias effect perspective)?\n:::\n\n:::{.fragment}\n[Centered: The change in the magnitude of the bias effect for a one unit change in defendant race (White to Black).]{style=\"color:blue;\"}      \n\n[Dummy/White as 0: The change in the magnitude of the bias effect for a one unit change in defendant race (White to Black).]{style=\"color:blue;\"}      \n\n[Dummy/Black as 0: The change in the magnitude of the bias effect for a one unit change in defendant race (Black to White).]{style=\"color:blue;\"}   \n:::\n--------------------------------------------------------------------------------\n\n**Centered model**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Dummy, White = 0**   \n$\\text{guilt} = 39.6 + 8.5*\\text{black defend} + 0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \n\n**Dummy, Black = 0**   \n$\\text{guilt} = 48.1 + -8.5*\\text{white defend} + 1.0*\\text{bias}_c + -.4*\\text{white defend}*\\text{bias}_c$   \n\n::: {.callout-important}\n# Exercise\nQuantify effect of bias from model formula (can use any model).\n:::\n\n--------------------------------------------------------------------------------\n\n**From Dummy, White = 0 model**  \n\n[For White defendants:]{style=\"color:blue;\"}\n    \nBias effect = $0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \nBias effect = $0.6*\\text{bias}_c + .4*0*\\text{bias}_c$  \nBias effect = $0.6*\\text{bias}_c$\n\n[For Black defendants:}{style=\"color:blue;\"}     \n\nBias effect = $0.6*\\text{bias}_c + .4*\\text{black defend}*\\text{bias}_c$  \nBias effect = $0.6*\\text{bias}_c + .4*1*\\text{bias}_c$  \nBias effect = $1.0*\\text{bias}_c$\n    \n--------------------------------------------------------------------------------\n\n## Quantitative & Dichotomous: Dichotomous *simple* effects   \n\n::: {.callout-important}\n# Question\nHow do you test simple effects of defendant race at various levels of bias (and what levels might you choose to test)?\n:::\n\n:::{.fragment}\n[We want to report simple effects of defendant race at the mean of bias and one SD above and below mean (or other meaningful values).]{style=\"color:blue;\"}      \n\n[Make sure the that the levels of bias at $\\pm1$ SD are represented in your data!]{style=\"color:blue;\"}   \n\n[As we noted earlier, the coefficient for defendant race (8.5) from the centered model is the simple effect of defendant race at the mean of bias.]{style=\"color:blue;\"}       \n\n[We need to perform two more transformations of bias to get the other simple effect tests for defendant race.]{style=\"color:blue;\"}      \n:::\n\n--------------------------------------------------------------------------------\n\n**Centered model**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$    \n\nBias is centered such that 0 = mean of bias.  \n\nWe need to transform bias such that 0 = +1 SD of bias or -1 SD of bias.  \n\nIt is counter-intuitive so be careful!   \n\n+1 SD = 0   \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(bias_hi = bias_c - sd(bias_c))\n```\n:::\n\n\n\n-1 SD = 0    \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data |> \n  mutate(bias_lo = bias_c + sd(bias_c))\n```\n:::\n\n\n\n*Note*: It is easy to confuse these transformations. Do a logical check on your results.   \n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_bias_hi = lm(guilt ~ black_defend_c * bias_hi, data = data)\n\nm_bias_hi |> \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                   estimate std.error statistic   p.value\n  <chr>                     <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)              56.7      1.06       53.4  1.07e-133\n2 black_defend_c           15.2      2.13        7.15 1.09e- 11\n3 bias_hi                   0.797    0.0466     17.1  3.24e- 43\n4 black_defend_c:bias_hi    0.415    0.0932      4.45 1.31e-  5\n```\n\n\n:::\n:::\n\n\n\nFor Jurors who are highly biased, Black defendants are rated 15.2 units more guilty than White defendants. \n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_bias_lo = lm(guilt ~ black_defend_c * bias_lo, data = data)\n\nm_bias_lo |> \n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                   estimate std.error statistic  p.value\n  <chr>                     <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)              31.0      1.06      29.1   4.03e-80\n2 black_defend_c            1.80     2.13       0.846 3.99e- 1\n3 bias_lo                   0.797    0.0466    17.1   3.24e-43\n4 black_defend_c:bias_lo    0.415    0.0932     4.45  1.31e- 5\n```\n\n\n:::\n:::\n\n\n\nFor Jurors who are highly unbiased, Black defendants are rated 1.8 units more guilty than White defendants. \n\n--------------------------------------------------------------------------------\n\n**Mean centered bias**   \n\n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Centered on -1 SD for bias**   \n$\\text{guilt} = 31.0 + 1.8*\\text{black defend}_c + 0.8*\\text{bias}_l + .4*\\text{black defend}_c*\\text{bias}_l$  \n\n**Centered on +1 SD for bias**   \n$\\text{guilt} = 56.7 + 15.2*\\text{black defend}_c + 0.8*\\text{bias}_h + .4*\\text{black defend}_c*\\text{bias}_h$  \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of the intercept in each model?\n:::\n\n:::{.fragment}\n[Mean: Predicted guilt rating unweighted across defendant race for juror of average bias.]{style=\"color:blue;\"}      \n\n[-1 SD: Predicted guilt rating for jurors who are low on bias, unweighted across defendant race.]{style=\"color:blue;\"}        \n\n[+1 SD: Predicted guilt rating for jurors who are high on bias, unweighted across defendant race.]{style=\"color:blue;\"}   \n:::\n\n--------------------------------------------------------------------------------\n\n**Mean centered bias**   \n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Centered on -1 SD for bias**   \n$\\text{guilt} = 31.0 + 1.8*\\text{black defend}_c + 0.8*\\text{bias}_l + .4*\\text{black defend}_c*\\text{bias}_l$  \n\n**Centered on +1 SD for bias**   \n$\\text{guilt} = 56.7 + 15.2*\\text{black defend}_c + 0.8*\\text{bias}_h + .4*\\text{black defend}_c*\\text{bias}_h$  \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of $b$ for defendant race in each model?\n:::\n\n:::{.fragment}\n[Mean: The contrast of mean guilt ratings for Black vs. White defendants for jurors of average bias (main effect).]{style=\"color:blue;\"}    \n\n[-1 SD: The contrast of mean guilt ratings for Black vs. White defendants for jurors low on bias (simple effect).]{style=\"color:blue;\"}    \n\n[+1 SD: The contrast of mean guilt ratings for Black vs. White defendants for jurors high on bias (simple effect).]{style=\"color:blue;\"}   \n:::\n\n--------------------------------------------------------------------------------\n\n**Mean centered bias**   \n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Centered on -1 SD for bias**   \n$\\text{guilt} = 31.0 + 1.8*\\text{black defend}_c + 0.8*\\text{bias}_l + .4*\\text{black defend}_c*\\text{bias}_l$  \n\n**Centered on +1 SD for bias**   \n$\\text{guilt} = 56.7 + 15.2*\\text{black defend}_c + 0.8*\\text{bias}_h + .4*\\text{black defend}_c*\\text{bias}_h$  \n\n::: {.callout-important}\n# Question\nWhat are the interpretations of $b$ for bias in each model?\n:::\n\n:::{.fragment}\n[Mean: The change in guilt for a 1 unit increase in bias, unweighted across defendant race.]{style=\"color:blue;\"}    \n\n[-1 SD: The change in guilt for a 1 unit increase in bias, unweighted across defendant race.]{style=\"color:blue;\"}    \n\n[+1 SD: The change in guilt for a 1 unit increase in bias, unweighted across defendant race.]{style=\"color:blue;\"}    \n:::\n\n--------------------------------------------------------------------------------\n\n**Mean centered bias**   \n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Centered on -1 SD for bias**   \n$\\text{guilt} = 31.0 + 1.8*\\text{black defend}_c + 0.8*\\text{bias}_l + .4*\\text{black defend}_c*\\text{bias}_l$  \n\n**Centered on +1 SD for bias**   \n$\\text{guilt} = 56.7 + 15.2*\\text{black defend}_c + 0.8*\\text{bias}_h + .4*\\text{black defend}_c*\\text{bias}_h$  \n\n:::{.callout-important}\n# Question\nWhat are the interpretations of $b$ for product term in each model (from a defendant race effect perspective)?\n:::\n\n:::{.fragment}\n[Mean: The change in the magnitude of the defendant race effect for a one unit change in juror bias.]{style=\"color:blue;\"}    \n\n[-1 SD: The change in the magnitude of the defendant race effect for a one unit change in juror bias.]{style=\"color:blue;\"}   \n\n[+1 SD: The change in the magnitude of the defendant race effect for a one unit change in juror bias.]{style=\"color:blue;\"}    \n:::\n\n--------------------------------------------------------------------------------\n\n**Mean centered bias**   \n$\\text{guilt} = 43.9 + 8.5*\\text{black defend}_c + 0.8*\\text{bias}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \n\n**Centered on -1 SD for bias**   \n$\\text{guilt} = 31.0 + 1.8*\\text{black defend}_c + 0.8*\\text{bias}_l + .4*\\text{black defend}_c*\\text{bias}_l$  \n\n**Centered on +1 SD for bias**   \n$\\text{guilt} = 56.7 + 15.2*\\text{black defend}_c + 0.8*\\text{bias}_h + .4*\\text{black defend}_c*\\text{bias}_h$  \n\n::: {.callout-important}\n# Exercise\nQuantify effect of defendant race from model formula (can use any model).\n:::\n\n--------------------------------------------------------------------------------\n\n**From centered model**  \n[Mean:]{style=\"color:blue;\"}\n    \nDefendant race effect = $8.5*\\text{black defend}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \nDefendant race effect = $8.5*\\text{black defend}_c + .4*\\text{black defend}_c*0$  \nDefendant race effect = $8.5*\\text{black defend}_c$\n\n[-1 SD:]{style=\"color:blue;\"}\n\nDefendant race effect = $8.5*\\text{black defend}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \nDefendant race effect = $8.5*\\text{black defend}_c + .4*\\text{black defend}_c*-16.2$  \nDefendant race effect = $1.8*\\text{black defend}_c$ (w/rounding error)\n\n[+1 SD:]{style=\"color:blue;\"}\n\nDefendant race effect = $8.5*\\text{black defend}_c + .4*\\text{black defend}_c*\\text{bias}_c$  \nDefendant race effect = $8.5*\\text{black defend}_c + .4*\\text{black defend}_c*16.2$  \nDefendant race effect = $15.2*\\text{black defend}_c$ (w/rounding error)\n\n--------------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_int +\n  geom_vline(xintercept = mean(data$bias) + sd(data$bias), linewidth = .75) +\n  geom_vline(xintercept = mean(data$bias) - sd(data$bias), linewidth = .75)\n```\n\n::: {.cell-output-display}\n![](11_interactions_quantitative_and_dichotomous_files/figure-revealjs/unnamed-chunk-31-1.png){width=960}\n:::\n:::\n\n\n\n--------------------------------------------------------------------------------\n\n## A sample brief report:  Defendant race is focal\n\nDefendant guilt ratings were analyzed in a General Linear Model with defendant race (Black vs. White) as a dichotomous variable and juror implicit bias (mean centered) as a quantitative variable. The interaction between these two variables was also included in the model.    \n\nThe overall model accounted for a significant amount of variance in guilt ratings, $R^2= 0.59, F(3,236) = 114.00, p < .001$.  A significant main effect of defendant race was observed, 95% CI($b$)= [5.5,11.5], $\\Delta R^2=.06, t(236) = 5.66, p < .001$, such that Black defendants were rated as 8.5 units more guilty than White defendants among jurors of mean bias. However, juror bias significantly moderated the defendant race effect, 95% CI($b$)= [0.2,0.6], $\\Delta R^2=.03, t(236) = 4.45, p < .001$, indicating that the magnitude of the defendant race effect increased by 0.4 units for every one unit increase in juror bias (see Figure 1). Given this, the simple effect of defendant race was substantially reduced and non-significant among jurors who were low on bias (1 SD below the mean), 95% CI($b$)= [-2.4,5.6], $\\Delta R^2=.00, t(236)= 0.85, p= .399$. In contrast, the effect of defendant race was substantially larger and significant among jurors who were high on bias, 95% CI($b$)= [11.0,19.4], $\\Delta R^2=.09, t(236)= 7.15, p < .001$.\n",
    "supporting": [
      "11_interactions_quantitative_and_dichotomous_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}